# autoexec.R: the file a bundle's programs source first, generated by the
# translation and maintained by a person afterwards (ADR 0004).
#
# The contract under test: every program's header finds autoexec.R from its
# own file -- source(), sys.source(), Rscript, R CMD BATCH -- or, for pasted
# code, from the working directory, and sources it with chdir = TRUE; autoexec.R
# holds the library paths a person edits, loads the helpers and formats, and
# reads a relative path as inside its own folder; and sourcing it by hand once
# per session is the R counterpart of a SAS autoexec.

canonical <- function(path) normalizePath(path, winslash = "/", mustWork = FALSE)

# A bundle with a work library only, as the emitter writes one with no project.
autoexec_fixture <- function(bundle, program = character()) {
  write_helpers(bundle)
  write_formats(list(), bundle)
  write_autoexec(NULL, bundle)
  if (length(program)) {
    writeLines(c(module_bootstrap(), program), file.path(bundle, "prog.R"))
  }
  invisible(bundle)
}

test_that("the bootstrap header is one guarded line under a two-line comment", {
  hdr <- module_bootstrap()
  # The whole point: a reader opening a program meets the translation, not a
  # page of plumbing. No file-location search either (ADR 0004): programs run
  # where their autoexec is.
  expect_length(hdr, 3L)
  expect_false(any(grepl("sys\\.frames|sys\\.function|ofile|commandArgs", hdr)))
  # Agent staging decides whether a module already carries the header by this
  # phrase, and the gate skips the block by its guard on `.sas2r_registry`.
  expect_true(any(grepl("sas2r bootstrap", hdr, fixed = TRUE)))
  exprs <- parse(text = hdr)
  expect_length(exprs, 1L)
  expect_match(paste(deparse(exprs[[1L]][[2L]]), collapse = " "),
               ".sas2r_registry", fixed = TRUE)
  expect_true(any(grepl('"autoexec.R"', hdr, fixed = TRUE)))
  expect_true(any(grepl("chdir = TRUE", hdr, fixed = TRUE)))
  expect_false(any(grepl("_sas2r_registry\\.R|_sas2r_boot\\.R|sas2r-helpers\\.R|_sas2r_formats\\.R", hdr)))
})

test_that("write_autoexec writes a person's file: settings first, loading last, no locator", {
  bundle <- withr::local_tempdir()
  autoexec_fixture(bundle)
  path <- file.path(bundle, "autoexec.R")
  expect_true(file.exists(path))
  expect_false(file.exists(file.path(bundle, "_sas2r_registry.R")))
  lines <- readLines(path, warn = FALSE)
  expect_match(lines[[1L]], "^# autoexec.R -- generated by sas2r .*, then yours to maintain\\.$")
  libs <- grep("^# ---- LIBRARIES", lines)
  load <- grep("^# ---- LOAD", lines)
  expect_length(libs, 1L)
  expect_length(load, 1L)
  expect_lt(libs, load)
  # The settings are plain strings a person edits; the loading has no
  # file-location search, because the file is always sourced with chdir.
  expect_true(any(grepl('work = list(read_path = "work", write_path = "work", engine = "rds", write = "rds")',
                        lines, fixed = TRUE)))
  expect_false(any(grepl("sys\\.frames|sys\\.function|commandArgs|sys\\.nframe", lines)))
  expect_true(any(grepl("sas2r_resolve_registry(.sas2r_registry, .sas2r_bundle_root)",
                        lines, fixed = TRUE)))

  e <- new.env(parent = globalenv())
  withr::with_dir(withr::local_tempdir(), source(path, local = e, chdir = TRUE))
  expect_identical(e$.sas2r_bundle_root, canonical(bundle))
  expect_identical(e$.sas2r_registry$work$write_path, file.path(canonical(bundle), "work"))
  expect_true(dir.exists(file.path(bundle, "work")))
  expect_true(is.function(get("lib_read", envir = e, inherits = FALSE)))
  expect_true(exists(".sas2r_formats", envir = e, inherits = FALSE))
  expect_false(exists(".sas2r_registry", envir = globalenv(), inherits = FALSE))
  expect_false(exists(".sas2r_bundle_root", envir = globalenv(), inherits = FALSE))
})

test_that("autoexec.R sourced from elsewhere without chdir stops with the fix; setwd() is the other way in", {
  bundle <- withr::local_tempdir()
  autoexec_fixture(bundle)
  e <- new.env(parent = globalenv())
  expect_error(
    withr::with_dir(withr::local_tempdir(), source(file.path(bundle, "autoexec.R"), local = e)),
    "chdir = TRUE")
  e2 <- new.env(parent = globalenv())
  expect_no_error(withr::with_dir(bundle, source("autoexec.R", local = e2)))
  expect_identical(e2$.sas2r_bundle_root, canonical(bundle))
})

test_that("a program runs from its folder and after the autoexec; from elsewhere it fails on its first line", {
  bundle <- withr::local_tempdir()
  autoexec_fixture(bundle, c(
    "adsl <- data.frame(x = 1:3)",
    'lib_write(adsl, "work", "adsl")',
    'cat("BOOT_OK\\n")'
  ))
  elsewhere <- withr::local_tempdir()
  written <- file.path(bundle, "work", "adsl.rds")

  # From the run folder, into a sandbox: the runtime lands in the sandbox, and
  # the working directory is back where it was afterwards.
  e1 <- new.env(parent = globalenv())
  wd_after <- withr::with_dir(bundle, {
    source("prog.R", local = e1)
    getwd()
  })
  expect_identical(canonical(wd_after), canonical(bundle))
  expect_identical(e1$.sas2r_bundle_root, canonical(bundle))
  expect_true(file.exists(written))
  expect_false(exists(".sas2r_registry", envir = globalenv(), inherits = FALSE))

  # Rscript from the run folder, as a batch job runs.
  unlink(file.path(bundle, "work"), recursive = TRUE)
  r <- callr::rscript(file.path(bundle, "prog.R"), wd = bundle,
                      show = FALSE, fail_on_status = FALSE)
  expect_identical(r$status, 0L)
  expect_match(r$stdout, "BOOT_OK", fixed = TRUE)
  expect_true(file.exists(written))

  # A module staged in a subfolder runs from the run folder too.
  dir.create(file.path(bundle, "inc"))
  writeLines(c(module_bootstrap(), 'cat("SUB_OK\\n")'), file.path(bundle, "inc", "sub.R"))
  r2 <- callr::rscript(file.path(bundle, "inc", "sub.R"), wd = bundle,
                       show = FALSE, fail_on_status = FALSE)
  expect_identical(r2$status, 0L)
  expect_match(r2$stdout, "SUB_OK", fixed = TRUE)

  # A driver launched elsewhere works when its working directory is the run
  # folder, which is the convention, and not otherwise.
  driver <- file.path(elsewhere, "driver.R")
  writeLines(sprintf("source(%s)", deparse(file.path(bundle, "prog.R"))), driver)
  unlink(file.path(bundle, "work"), recursive = TRUE)
  r3 <- callr::rscript(driver, wd = bundle, show = FALSE, fail_on_status = FALSE)
  expect_identical(r3$status, 0L)
  expect_true(file.exists(written))

  # From an unrelated working directory before the autoexec has run, the first
  # line fails because autoexec.R is not there: Rscript, a driver, source(),
  # and sys.source() alike.
  r4 <- callr::rscript(file.path(bundle, "prog.R"), wd = elsewhere,
                       show = FALSE, fail_on_status = FALSE)
  expect_false(identical(r4$status, 0L))
  expect_match(r4$stderr, "autoexec\\.R")
  r5 <- callr::rscript(driver, wd = elsewhere, show = FALSE, fail_on_status = FALSE)
  expect_false(identical(r5$status, 0L))
  expect_match(r5$stderr, "autoexec\\.R")
  # In-process, R's error says "cannot open the connection" and its warning
  # names autoexec.R; both reach a person at the console.
  e2 <- new.env(parent = globalenv())
  expect_warning(
    expect_error(withr::with_dir(elsewhere, source(file.path(bundle, "prog.R"), local = e2)),
                 "cannot open"),
    "autoexec\\.R")
  expect_warning(
    expect_error(withr::with_dir(elsewhere, sys.source(file.path(bundle, "prog.R"), envir = e2)),
                 "cannot open"),
    "autoexec\\.R")
  expect_false(dir.exists(file.path(elsewhere, "work")))
})

test_that("sourcing autoexec.R once per session is an autoexec: programs then skip their bootstrap", {
  bundle <- withr::local_tempdir()
  autoexec_fixture(bundle, 'adsl <- lib_read("work", "input")')

  e <- new.env(parent = globalenv())
  withr::with_dir(withr::local_tempdir(),
                  source(file.path(bundle, "autoexec.R"), local = e, chdir = TRUE))
  marker <- function(libref, member) data.frame(x = 1:7)
  e$lib_read <- marker
  withr::with_dir(withr::local_tempdir(),
                  sys.source(file.path(bundle, "prog.R"), envir = e))
  # The header found the runtime already loaded and sourced nothing over it.
  expect_identical(e$lib_read, marker)
  expect_identical(nrow(e$adsl), 7L)
})

test_that("a run folder moved as a whole keeps working, and writes inside its new location", {
  root <- withr::local_tempdir()
  writeLines("data work.prepped; set work.input; run;", file.path(root, "prep.sas"))
  out <- withr::local_tempdir()
  suppressMessages(sas_transpile(sas_project(file.path(root, "prep.sas")), out))

  # `work` is written relative to the folder, never as the folder the
  # translation happened to land in.
  txt <- readLines(file.path(out, "autoexec.R"), warn = FALSE)
  expect_true(any(grepl('write_path = "work"', txt, fixed = TRUE)))
  expect_false(any(grepl(canonical(out), txt, fixed = TRUE)))

  dir.create(file.path(out, "work"))
  saveRDS(data.frame(x = 1:3), file.path(out, "work", "input.rds"))
  moved <- file.path(withr::local_tempdir(), "moved_run")
  expect_true(file.rename(out, moved))

  r <- callr::rscript(file.path(moved, "prep.R"), wd = moved,
                      show = FALSE, fail_on_status = FALSE)
  expect_identical(r$status, 0L)
  expect_true(file.exists(file.path(moved, "work", "prepped.rds")))
  expect_identical(nrow(readRDS(file.path(moved, "work", "prepped.rds"))), 3L)
  expect_false(dir.exists(out))
})

test_that("paths inside the bundle are written relative, outside absolute, and a hand edit takes effect", {
  root <- withr::local_tempdir()
  data_dir <- file.path(root, "data"); dir.create(data_dir)
  saveRDS(data.frame(USUBJID = c("01", "02")), file.path(data_dir, "adsl.rds"))
  writeLines("data adam.x; set adam.adsl; run;", file.path(root, "p.sas"))
  p <- sas_project(file.path(root, "p.sas"),
                   config = list(libraries = list(adam = data_dir)))
  out <- withr::local_tempdir()
  write_helpers(out)
  write_formats(list(), out)
  write_autoexec(p, out, library_map = build_attempt_library_map(p, out))
  txt <- paste(readLines(file.path(out, "autoexec.R"), warn = FALSE), collapse = "\n")

  # The source library lives outside the bundle: absolute, as configured.
  # Everything sas2r writes lives inside it: a bare relative name.
  expect_true(grepl(paste0('adam = list(read_path = "', canonical(data_dir),
                           '", write_path = "adam", engine = "sas7bdat", write = "rds")'),
                    txt, fixed = TRUE))
  expect_true(grepl('work = list(read_path = "work", write_path = "work"', txt, fixed = TRUE))
  expect_false(grepl(canonical(out), txt, fixed = TRUE))

  e <- new.env(parent = globalenv())
  withr::with_dir(withr::local_tempdir(),
                  source(file.path(out, "autoexec.R"), local = e, chdir = TRUE))
  expect_identical(e$.sas2r_registry$adam$read_path, canonical(data_dir))
  expect_identical(e$.sas2r_registry$adam$write_path, file.path(canonical(out), "adam"))
  expect_true(dir.exists(file.path(out, "adam")))
  expect_identical(nrow(e$lib_read("adam", "adsl")), 2L)

  # The source data moves; the person edits one line of autoexec.R.
  moved_data <- file.path(withr::local_tempdir(), "adam_v2"); dir.create(moved_data)
  file.copy(file.path(data_dir, "adsl.rds"), moved_data)
  unlink(file.path(data_dir, "adsl.rds"))
  lines <- readLines(file.path(out, "autoexec.R"), warn = FALSE)
  writeLines(sub(canonical(data_dir), moved_data, lines, fixed = TRUE),
             file.path(out, "autoexec.R"))
  e2 <- new.env(parent = globalenv())
  withr::with_dir(withr::local_tempdir(),
                  source(file.path(out, "autoexec.R"), local = e2, chdir = TRUE))
  expect_identical(e2$.sas2r_registry$adam$read_path, moved_data)
  expect_identical(nrow(e2$lib_read("adam", "adsl")), 2L)
})

test_that("an uncommented <FILL> placeholder is refused with the libref named", {
  root <- canonical(withr::local_tempdir())
  reg <- list(sdtm = list(read_path = "<FILL: ask your SAS admin>", write_path = "sdtm",
                          engine = "sas7bdat", write = "rds"))
  expect_error(sas2r_resolve_registry(reg, root), "sdtm", class = "sas2r_registry_fill")
  expect_false(dir.exists(file.path(root, "sdtm")))
  # A resolved registry is absolute everywhere, and the write directories exist.
  ok <- sas2r_resolve_registry(
    list(adam = list(read_path = "/study/adam", write_path = "adam", engine = "sas7bdat", write = "rds")),
    root)
  expect_identical(ok$adam$read_path, "/study/adam")
  expect_identical(ok$adam$write_path, file.path(root, "adam"))
  expect_true(dir.exists(file.path(root, "adam")))
})

test_that("every emitter writes autoexec.R, and no registry or boot file", {
  root <- withr::local_tempdir()
  writeLines("data work.b; set work.a; run;", file.path(root, "prog.sas"))
  out <- withr::local_tempdir()
  suppressMessages(sas_transpile(sas_project(file.path(root, "prog.sas")), out))
  present <- intersect(list.files(out),
                       c(SAS2R_BUNDLE_FILES, "_sas2r_registry.R", "_sas2r_boot.R"))
  expect_setequal(present, SAS2R_BUNDLE_FILES)
})
