test_that("a bundle attempt executes the programs that are not deferred and records its scope", {
  fx <- repair_workflow_fixture(n = 3L, failures = integer())
  state <- fx$state
  state$diagnostics$deferred_components <- list(p02 = "p02 (work.missing)")
  rec <- run_bundle_attempt(state)
  expect_true(rec$passed)
  expect_identical(rec$execution_order, c("p01", "p03"))
  expect_identical(rec$executed_component_ids, c("p01", "p03"))
  expect_identical(rec$execution_scope, "partial")
  expect_identical(rec$deferred_component_ids, "p02")
  expect_identical(rec$deferred_reasons$p02, "p02 (work.missing)")
  outputs <- names(rec$output_hashes)
  expect_true(any(grepl("out1", outputs, fixed = TRUE)))
  expect_true(any(grepl("out3", outputs, fixed = TRUE)))
  expect_false(any(grepl("out2", outputs, fixed = TRUE)))
  assessment <- assess_final_outputs(state$output_contracts, rec, state$graph, state$histories)
  expect_identical(assessment$targets$work.out2$status, "not_executed")
  expect_match(assessment$targets$work.out2$reason, "p02 (work.missing)", fixed = TRUE)
  expect_true(assessment$targets$work.out1$passed)
  expect_true(assessment$targets$work.out3$passed)
  expect_identical(assessment$status, "needs_review")
})

test_that("a complete attempt records its scope and can still become migration-ready", {
  fx <- repair_workflow_fixture(n = 1L, failures = integer())
  rec <- run_bundle_attempt(fx$state)
  expect_identical(rec$execution_scope, "complete")
  expect_length(rec$deferred_component_ids, 0L)
  assessment <- assess_final_outputs(fx$state$output_contracts, rec, fx$state$graph, fx$state$histories)
  expect_identical(assessment$status, "migration_ready")
})
