# autoexec.R: the file a bundle's programs source first, generated by the
# translation and maintained by a person afterwards (ADR 0004).
#
# The contract under test: every program's header finds autoexec.R from its
# own file -- source(), sys.source(), Rscript, R CMD BATCH -- or, for pasted
# code, from the working directory, and sources it with chdir = TRUE; autoexec.R
# holds the library paths a person edits, loads the helpers and formats, and
# reads a relative path as inside its own folder; and sourcing it by hand once
# per session is the R counterpart of a SAS autoexec.

canonical <- function(path) normalizePath(path, winslash = "/", mustWork = FALSE)

# A bundle with a work library only, as the emitter writes one with no project.
autoexec_fixture <- function(bundle, program = character()) {
  write_helpers(bundle)
  write_formats(list(), bundle)
  write_autoexec(NULL, bundle)
  if (length(program)) {
    writeLines(c(module_bootstrap(), program), file.path(bundle, "prog.R"))
  }
  invisible(bundle)
}

test_that("the bootstrap header is one guarded line under a two-line comment", {
  hdr <- module_bootstrap()
  # The whole point: a reader opening a program meets the translation, not a
  # page of plumbing. No file-location search either (ADR 0004): programs run
  # where their autoexec is.
  expect_length(hdr, 3L)
  expect_false(any(grepl("sys\\.frames|sys\\.function|ofile|commandArgs", hdr)))
  # Agent staging decides whether a module already carries the header by this
  # phrase, and the gate skips the block by its guard on `.sas2r_registry`.
  expect_true(any(grepl("sas2r bootstrap", hdr, fixed = TRUE)))
  exprs <- parse(text = hdr)
  expect_length(exprs, 1L)
  expect_match(paste(deparse(exprs[[1L]][[2L]]), collapse = " "),
               ".sas2r_registry", fixed = TRUE)
  expect_true(any(grepl('"autoexec.R"', hdr, fixed = TRUE)))
  expect_true(any(grepl("chdir = TRUE", hdr, fixed = TRUE)))
  expect_false(any(grepl("_sas2r_registry\\.R|_sas2r_boot\\.R|sas2r-helpers\\.R|_sas2r_formats\\.R", hdr)))
})

test_that("write_autoexec writes a person's file: settings first, loading last, no locator", {
  bundle <- withr::local_tempdir()
  autoexec_fixture(bundle)
  path <- file.path(bundle, "autoexec.R")
  expect_true(file.exists(path))
  expect_false(file.exists(file.path(bundle, "_sas2r_registry.R")))
  lines <- readLines(path, warn = FALSE)
  expect_match(lines[[1L]], "^# autoexec.R -- generated by sas2r .*, then yours to maintain\\.$")
  libs <- grep("^# ---- LIBRARIES", lines)
  load <- grep("^# ---- LOAD", lines)
  expect_length(libs, 1L)
  expect_length(load, 1L)
  expect_lt(libs, load)
  # The settings are plain strings a person edits; the loading has no
  # file-location search, because the file is always sourced with chdir.
  expect_true(any(grepl('work = list(read_path = "work", write_path = "work", engine = "rds", write = "rds")',
                        lines, fixed = TRUE)))
  expect_false(any(grepl("sys\\.frames|sys\\.function|commandArgs|sys\\.nframe", lines)))
  expect_true(any(grepl("sas2r_resolve_registry(.sas2r_registry, .sas2r_bundle_root)",
                        lines, fixed = TRUE)))

  e <- new.env(parent = globalenv())
  withr::with_dir(withr::local_tempdir(), source(path, local = e, chdir = TRUE))
  expect_identical(e$.sas2r_bundle_root, canonical(bundle))
  expect_identical(e$.sas2r_registry$work$write_path, file.path(canonical(bundle), "work"))
  expect_true(dir.exists(file.path(bundle, "work")))
  expect_true(is.function(get("lib_read", envir = e, inherits = FALSE)))
  expect_true(exists(".sas2r_formats", envir = e, inherits = FALSE))
  expect_false(exists(".sas2r_registry", envir = globalenv(), inherits = FALSE))
  expect_false(exists(".sas2r_bundle_root", envir = globalenv(), inherits = FALSE))
})

test_that("autoexec.R sourced from elsewhere without chdir stops with the fix; setwd() is the other way in", {
  bundle <- withr::local_tempdir()
  autoexec_fixture(bundle)
  e <- new.env(parent = globalenv())
  expect_error(
    withr::with_dir(withr::local_tempdir(), source(file.path(bundle, "autoexec.R"), local = e)),
    "chdir = TRUE")
  e2 <- new.env(parent = globalenv())
  expect_no_error(withr::with_dir(bundle, source("autoexec.R", local = e2)))
  expect_identical(e2$.sas2r_bundle_root, canonical(bundle))
})

test_that("a run folder moved as a whole keeps working, and writes inside its new location", {
  root <- withr::local_tempdir()
  writeLines("data work.prepped; set work.input; run;", file.path(root, "prep.sas"))
  out <- withr::local_tempdir()
  suppressMessages(sas_transpile(sas_project(file.path(root, "prep.sas")), out))

  # `work` is written relative to the folder, never as the folder the
  # translation happened to land in.
  txt <- readLines(file.path(out, "autoexec.R"), warn = FALSE)
  expect_true(any(grepl('write_path = "work"', txt, fixed = TRUE)))
  expect_false(any(grepl(canonical(out), txt, fixed = TRUE)))

  dir.create(file.path(out, "work"))
  saveRDS(data.frame(x = 1:3), file.path(out, "work", "input.rds"))
  moved <- file.path(withr::local_tempdir(), "moved_run")
  expect_true(file.rename(out, moved))

  r <- callr::rscript(file.path(moved, "prep.R"), wd = moved,
                      show = FALSE, fail_on_status = FALSE)
  expect_identical(r$status, 0L)
  expect_true(file.exists(file.path(moved, "work", "prepped.rds")))
  expect_identical(nrow(readRDS(file.path(moved, "work", "prepped.rds"))), 3L)
  expect_false(dir.exists(out))
})

test_that("an uncommented <FILL> placeholder is refused with the libref named", {
  root <- canonical(withr::local_tempdir())
  reg <- list(sdtm = list(read_path = "<FILL: ask your SAS admin>", write_path = "sdtm",
                          engine = "sas7bdat", write = "rds"))
  expect_error(sas2r_resolve_registry(reg, root), "sdtm", class = "sas2r_registry_fill")
  expect_false(dir.exists(file.path(root, "sdtm")))
  # A resolved registry is absolute everywhere, and the write directories exist.
  ok <- sas2r_resolve_registry(
    list(adam = list(read_path = "/study/adam", write_path = "adam", engine = "sas7bdat", write = "rds")),
    root)
  expect_identical(ok$adam$read_path, "/study/adam")
  expect_identical(ok$adam$write_path, file.path(root, "adam"))
  expect_true(dir.exists(file.path(root, "adam")))
})

test_that("every emitter writes autoexec.R, and no registry or boot file", {
  root <- withr::local_tempdir()
  writeLines("data work.b; set work.a; run;", file.path(root, "prog.sas"))
  out <- withr::local_tempdir()
  suppressMessages(sas_transpile(sas_project(file.path(root, "prog.sas")), out))
  present <- intersect(list.files(out),
                       c(SAS2R_BUNDLE_FILES, "_sas2r_registry.R", "_sas2r_boot.R"))
  expect_setequal(present, SAS2R_BUNDLE_FILES)
})
