# The bundle boot file and the header every translated program carries.
#
# The contract under test: a program locates `_sas2r_boot.R` from its own file
# -- source(), sys.source(), Rscript, R CMD BATCH -- or, for pasted code, from
# the working directory; the boot file loads the registry, helpers, and formats
# once into the environment it is sourced into; and every path inside the
# bundle is recorded relative to the bundle root, so a run folder moved as a
# whole keeps working.

boot_fixture <- function(bundle, program = character()) {
  write_helpers(bundle)
  writeLines(c(
    ".sas2r_registry <- list(",
    "  work = list(read_path = file.path(.sas2r_bundle_root, \"work\"),",
    "              write_path = file.path(.sas2r_bundle_root, \"work\"),",
    "              engine = \"rds\", write = \"rds\")",
    ")",
    "dir.create(.sas2r_registry$work$write_path, showWarnings = FALSE, recursive = TRUE)"
  ), file.path(bundle, "_sas2r_registry.R"))
  write_formats(list(), bundle)
  write_boot(bundle)
  if (length(program)) {
    writeLines(c(module_bootstrap(), program), file.path(bundle, "prog.R"))
  }
  invisible(bundle)
}

canonical <- function(path) normalizePath(path, winslash = "/", mustWork = FALSE)

test_that("the bootstrap header is short, and names only the boot file", {
  hdr <- module_bootstrap()
  # The whole point of the boot file: a reader opening a program meets the
  # translation, not a page of plumbing.
  expect_lte(length(hdr), 24L)
  # Agent staging decides whether a module already carries the header by this
  # phrase, and the gate skips the block by its guard on `.sas2r_registry`.
  expect_true(any(grepl("sas2r bootstrap", hdr, fixed = TRUE)))
  exprs <- parse(text = hdr)
  expect_length(exprs, 1L)
  expect_match(paste(deparse(exprs[[1L]][[2L]]), collapse = " "),
               ".sas2r_registry", fixed = TRUE)
  expect_true(any(grepl("_sas2r_boot.R", hdr, fixed = TRUE)))
  expect_false(any(grepl("_sas2r_registry\\.R|sas2r-helpers\\.R|_sas2r_formats\\.R", hdr)))
})

test_that("write_boot writes a boot file that loads the runtime trio into its caller's environment", {
  bundle <- withr::local_tempdir()
  boot_fixture(bundle)
  boot <- file.path(bundle, "_sas2r_boot.R")
  expect_true(file.exists(boot))
  lines <- readLines(boot, warn = FALSE)
  expect_match(lines[[1L]], "^# Generated by sas2r")
  expect_true(any(grepl('c("_sas2r_registry.R", "sas2r-helpers.R", "_sas2r_formats.R")',
                        lines, fixed = TRUE)))

  e <- new.env(parent = globalenv())
  withr::with_dir(withr::local_tempdir(), source(boot, local = e))
  expect_true(exists(".sas2r_registry", envir = e, inherits = FALSE))
  expect_true(is.function(get("lib_read", envir = e, inherits = FALSE)))
  expect_true(exists(".sas2r_formats", envir = e, inherits = FALSE))
  # The root is the boot file's own folder, whatever the working directory,
  # and the registry's bundle-relative paths resolved against it.
  expect_identical(e$.sas2r_bundle_root, canonical(bundle))
  expect_identical(e$.sas2r_registry$work$write_path,
                   file.path(canonical(bundle), "work"))
  expect_true(dir.exists(file.path(bundle, "work")))
  # Scratch bindings are tidied; nothing reached globalenv().
  expect_false(exists(".sas2r_boot_file", envir = e, inherits = FALSE))
  expect_false(exists(".sas2r_registry", envir = globalenv(), inherits = FALSE))
  expect_false(exists(".sas2r_bundle_root", envir = globalenv(), inherits = FALSE))
})

test_that("a program boots from source(), sys.source(), and Rscript, from any working directory", {
  bundle <- withr::local_tempdir()
  boot_fixture(bundle, c(
    "adsl <- data.frame(x = 1:3)",
    'lib_write(adsl, "work", "adsl")',
    'cat("BOOT_OK\\n")'
  ))
  elsewhere <- withr::local_tempdir()
  written <- file.path(bundle, "work", "adsl.rds")

  # source() from elsewhere, into a sandbox: the runtime lands in the sandbox.
  e1 <- new.env(parent = globalenv())
  withr::with_dir(elsewhere, source(file.path(bundle, "prog.R"), local = e1))
  expect_identical(e1$.sas2r_bundle_root, canonical(bundle))
  expect_true(file.exists(written))
  expect_false(exists(".sas2r_boot_root", envir = e1, inherits = FALSE))
  expect_false(exists(".sas2r_registry", envir = globalenv(), inherits = FALSE))

  # sys.source() from elsewhere.
  unlink(file.path(bundle, "work"), recursive = TRUE)
  e2 <- new.env(parent = globalenv())
  withr::with_dir(elsewhere, sys.source(file.path(bundle, "prog.R"), envir = e2))
  expect_true(file.exists(written))

  # Rscript from elsewhere.
  unlink(file.path(bundle, "work"), recursive = TRUE)
  r <- callr::rscript(file.path(bundle, "prog.R"), wd = elsewhere,
                      show = FALSE, fail_on_status = FALSE)
  expect_identical(r$status, 0L)
  expect_match(r$stdout, "BOOT_OK", fixed = TRUE)
  expect_true(file.exists(written))
  expect_false(dir.exists(file.path(elsewhere, "work")))
})

test_that("the boot file doubles as an autoexec: booted once, a program skips its own bootstrap", {
  bundle <- withr::local_tempdir()
  boot_fixture(bundle, 'adsl <- lib_read("work", "input")')

  e <- new.env(parent = globalenv())
  withr::with_dir(withr::local_tempdir(),
                  source(file.path(bundle, "_sas2r_boot.R"), local = e))
  marker <- function(libref, member) data.frame(x = 1:7)
  e$lib_read <- marker
  withr::with_dir(withr::local_tempdir(),
                  sys.source(file.path(bundle, "prog.R"), envir = e))
  # The header found the runtime already loaded and sourced nothing over it.
  expect_identical(e$lib_read, marker)
  expect_identical(nrow(e$adsl), 7L)
})

test_that("a run folder moved as a whole keeps working, and writes inside its new location", {
  root <- withr::local_tempdir()
  writeLines("data work.prepped; set work.input; run;", file.path(root, "prep.sas"))
  out <- withr::local_tempdir()
  suppressMessages(sas_transpile(sas_project(file.path(root, "prep.sas")), out))

  # The seed records `work` relative to the bundle root, never as the folder
  # the translation happened to be written to.
  reg <- readLines(file.path(out, "_sas2r_registry.R"), warn = FALSE)
  expect_true(any(grepl('file.path(.sas2r_bundle_root, "work")', reg, fixed = TRUE)))
  expect_false(any(grepl(canonical(out), reg, fixed = TRUE)))

  dir.create(file.path(out, "work"))
  saveRDS(data.frame(x = 1:3), file.path(out, "work", "input.rds"))
  moved <- file.path(withr::local_tempdir(), "moved_run")
  expect_true(file.rename(out, moved))

  elsewhere <- withr::local_tempdir()
  r <- callr::rscript(file.path(moved, "prep.R"), wd = elsewhere,
                      show = FALSE, fail_on_status = FALSE)
  expect_identical(r$status, 0L)
  expect_true(file.exists(file.path(moved, "work", "prepped.rds")))
  expect_identical(nrow(readRDS(file.path(moved, "work", "prepped.rds"))), 3L)
  expect_false(dir.exists(out))
  expect_false(dir.exists(file.path(elsewhere, "work")))
})

test_that("registry paths inside the bundle are relative to its root; paths outside stay absolute", {
  root <- withr::local_tempdir()
  data_dir <- file.path(root, "data"); dir.create(data_dir)
  writeLines("data adam.x; set adam.adsl; run;", file.path(root, "p.sas"))
  p <- sas_project(file.path(root, "p.sas"),
                   config = list(libraries = list(adam = data_dir)))
  out <- withr::local_tempdir()
  write_registry(p, out, library_map = build_attempt_library_map(p, out))
  reg <- paste(readLines(file.path(out, "_sas2r_registry.R"), warn = FALSE),
               collapse = "\n")

  # The source library lives outside the bundle: absolute, as configured.
  expect_true(grepl(paste0('read_path = "', canonical(data_dir), '"'), reg, fixed = TRUE))
  # Everything sas2r writes lives inside it: relative to the root.
  expect_true(grepl('write_path = file.path(.sas2r_bundle_root, "adam")', reg, fixed = TRUE))
  expect_true(grepl('work = list(read_path = file.path(.sas2r_bundle_root, "work")', reg, fixed = TRUE))
  expect_false(grepl(canonical(out), reg, fixed = TRUE))

  # Through the boot file the root is the bundle's own folder.
  write_helpers(out)
  write_formats(list(), out)
  write_boot(out)
  e <- new.env(parent = globalenv())
  withr::with_dir(withr::local_tempdir(),
                  source(file.path(out, "_sas2r_boot.R"), local = e))
  expect_identical(e$.sas2r_registry$adam$read_path, canonical(data_dir))
  expect_identical(e$.sas2r_registry$adam$write_path, file.path(canonical(out), "adam"))

  # Sourced on its own -- the interactive shortcut the vignette documents --
  # the registry takes the working directory as the root.
  e2 <- new.env(parent = globalenv())
  wd <- withr::with_dir(out, { source("_sas2r_registry.R", local = e2); getwd() })
  expect_identical(e2$.sas2r_registry$work$write_path, file.path(wd, "work"))
})

test_that("the boot file is written by every emitter and copied to the run folder", {
  root <- withr::local_tempdir()
  writeLines("data work.b; set work.a; run;", file.path(root, "prog.sas"))
  out <- withr::local_tempdir()
  suppressMessages(sas_transpile(sas_project(file.path(root, "prog.sas")), out))
  expect_true(file.exists(file.path(out, "_sas2r_boot.R")))
  expect_setequal(intersect(list.files(out), SAS2R_BUNDLE_FILES), SAS2R_BUNDLE_FILES)
})
