test_that("dataset deletion changes library visibility and preserves unrelated data", {
  dir <- withr::local_tempdir()
  env <- new.env(parent = baseenv())
  write_helpers(dir)
  sys.source(file.path(dir, "sas2r-helpers.R"), env)
  env$.sas2r_registry <- list(work = list(path = file.path(dir, "work"), write = "rds"))
  env$lib_write(data.frame(x = 1), "work", "one")
  env$lib_write(data.frame(x = 2), "work", "two")
  expect_equal(env$lib_read("work", "one")$x, 1)
  expect_identical(env$lib_delete("WORK", "ONE"), "one")
  expect_error(env$lib_read("work", "one"), "Dataset not found")
  expect_equal(env$lib_read("work", "two")$x, 2)
  expect_message(env$lib_delete("work", "one"), "Dataset not found")
  expect_error(env$lib_delete("work", "two:"), class = "sas2r_unsupported_dataset_delete")
  expect_error(env$lib_delete("work", "_ALL_"), class = "sas2r_unsupported_dataset_delete")
  expect_equal(env$lib_read("work", "two")$x, 2)
  expect_false(any(lint_r_code('lib_delete("work", c("one", "two"))')$level == "error"))
  expect_true(any(lint_r_code('file.remove("two.rds")')$kind == "banned_function"))
})

test_that("deleting a copy cannot expose or remove a separate original input", {
  dir <- withr::local_tempdir()
  inputs <- file.path(dir, "inputs"); dir.create(inputs)
  outputs <- file.path(dir, "outputs"); dir.create(outputs)
  saveRDS(data.frame(x = 9), file.path(inputs, "old.rds"))
  env <- new.env(parent = baseenv())
  write_helpers(dir)
  sys.source(file.path(dir, "sas2r-helpers.R"), env)
  env$.sas2r_registry <- list(adam = list(read_path = inputs, write_path = outputs, write = "rds"))
  env$lib_write(data.frame(x = 1), "adam", "old")
  env$lib_write(data.frame(x = 2), "adam", "new")
  expect_error(env$lib_delete("adam", c("new", "old")), class = "sas2r_unsupported_dataset_delete")
  expect_equal(readRDS(file.path(inputs, "old.rds"))$x, 9)
  expect_equal(env$lib_read("adam", "old")$x, 1)
  expect_equal(env$lib_read("adam", "new")$x, 2)
  expect_identical(env$lib_delete("adam", "new"), "new")
  expect_error(env$lib_read("adam", "new"), "Dataset not found")
})
