# Generated by sas2r -- self-contained runtime helpers. Do not edit by hand.
# NOTE: SAS || pads fixed-width operands; %+% does not. If source code relies on padded concatenation, review output widths.
`%+%` <- function(a, b) {
  paste0(ifelse(is.na(a), "", a), ifelse(is.na(b), "", b))
}

# SAS . not in (1, 2) is TRUE; NA %in% c(1, 2) is FALSE, so !(NA %in% ...) is TRUE
`%notin%` <- function(a, b) {
  if (is.character(a) || is.character(b)) {
    a <- if (is.character(a)) sub("\\s+$", "", a) else a
    b <- if (is.character(b)) sub("\\s+$", "", b) else b
  }
  !(a %in% b)
}

chr_cmp <- function(a, b, op = NULL) {
  if (missing(op) || is.null(op)) {
    if (is.character(a) || is.character(b)) {
      strip <- function(x) sub("\\s+$", "", x)
      a_chr <- strip(as.character(a))
      b_chr <- strip(as.character(b))
      a_na <- is.na(a) | a_chr == ""
      b_na <- is.na(b) | b_chr == ""

      res <- integer(max(length(a), length(b)))
      both_na <- a_na & b_na
      only_a_na <- a_na & !b_na
      only_b_na <- !a_na & b_na
      neither_na <- !a_na & !b_na

      res[both_na] <- 0L
      res[only_a_na] <- -1L
      res[only_b_na] <- 1L
      if (any(neither_na)) {
        lt <- a_chr < b_chr
        gt <- a_chr > b_chr
        res[neither_na & lt] <- -1L
        res[neither_na & gt] <- 1L
        res[neither_na & !lt & !gt] <- 0L
      }
      return(res)
    } else {
      a_val <- ifelse(is.na(a), -Inf, a)
      b_val <- ifelse(is.na(b), -Inf, b)
      res <- integer(max(length(a), length(b)))
      lt <- a_val < b_val
      gt <- a_val > b_val
      res[lt] <- -1L
      res[gt] <- 1L
      res[!lt & !gt] <- 0L
      return(res)
    }
  }
  if (is.character(a) || is.character(b)) {
    strip <- function(x) sub("\\s+$", "", x)
    a_chr <- strip(as.character(a))
    b_chr <- strip(as.character(b))
    a_na <- is.na(a) | a_chr == ""
    b_na <- is.na(b) | b_chr == ""

    both_na <- a_na & b_na
    only_a_na <- a_na & !b_na
    only_b_na <- !a_na & b_na
    neither_na <- !a_na & !b_na

    res <- logical(max(length(a), length(b)))

    if (op %in% c("==", "<=", ">=")) res[both_na] <- TRUE
    if (op %in% c("!=", "<", ">")) res[both_na] <- FALSE

    if (op %in% c("<", "<=", "!=")) res[only_a_na] <- TRUE
    if (op %in% c("==", ">", ">=")) res[only_a_na] <- FALSE

    if (op %in% c(">", ">=", "!=")) res[only_b_na] <- TRUE
    if (op %in% c("==", "<", "<=")) res[only_b_na] <- FALSE

    if (any(neither_na)) {
      cmp <- switch(op,
        "==" = a_chr == b_chr,
        "!=" = a_chr != b_chr,
        "<"  = a_chr < b_chr,
        "<=" = a_chr <= b_chr,
        ">"  = a_chr > b_chr,
        ">=" = a_chr >= b_chr
      )
      res[neither_na] <- cmp[neither_na]
    }
    return(res)
  } else {
    a_val <- ifelse(is.na(a), -Inf, a)
    b_val <- ifelse(is.na(b), -Inf, b)
    switch(op,
      "==" = a_val == b_val,
      "!=" = a_val != b_val,
      "<"  = a_val < b_val,
      "<=" = a_val <= b_val,
      ">"  = a_val > b_val,
      ">=" = a_val >= b_val
    )
  }
}

# SAS SUM()/MEAN() are row-wise across their arguments: each observation gets
# the sum/mean of its non-missing arguments, and only an observation whose
# arguments are all missing yields missing. Column aggregation (PROC MEANS,
# PROC SQL) is emitted inline by those emitters and never routed through these.
sas_sum <- function(...) {
  args <- list(...)
  if (length(args) == 0L) return(numeric(0))
  n <- max(vapply(args, length, integer(1)))
  if (n == 0L) return(numeric(0))
  total <- rep(0, n)
  any_ok <- rep(FALSE, n)
  for (a in args) {
    if (length(a) == 0L) next
    a <- rep_len(as.numeric(a), n)
    ok <- !is.na(a)
    total[ok] <- total[ok] + a[ok]
    any_ok <- any_ok | ok
  }
  total[!any_ok] <- NA_real_
  total
}

sas_mean <- function(...) {
  args <- list(...)
  if (length(args) == 0L) return(numeric(0))
  n <- max(vapply(args, length, integer(1)))
  if (n == 0L) return(numeric(0))
  total <- rep(0, n)
  cnt <- rep(0L, n)
  for (a in args) {
    if (length(a) == 0L) next
    a <- rep_len(as.numeric(a), n)
    ok <- !is.na(a)
    total[ok] <- total[ok] + a[ok]
    cnt[ok] <- cnt[ok] + 1L
  }
  out <- rep(NA_real_, n)
  has <- cnt > 0L
  out[has] <- total[has] / cnt[has]
  out
}

sas_round <- function(x, unit = 1) {
  # SAS rounds half away from zero; R's round() is banker's rounding.
  sign(x) * floor(abs(x) / unit + 0.5) * unit
}

sas_compress <- function(x, chars = " ") gsub(paste0("[", chars, "]"), "", x)

sas_substr <- function(x, pos, len = NULL) {
  if (is.null(len)) substr(x, pos, nchar(x))
  else substr(x, pos, pmax(pos + len - 1L, pos - 1L))
}

sas_min <- function(...) {
  args <- list(...)
  if (length(args) == 0L) return(numeric(0))
  # SAS MIN(x) with one argument is x, elementwise -- never a column aggregate.
  if (length(args) == 1L) return(args[[1]])
  res <- do.call(pmin, c(args, list(na.rm = TRUE)))
  all_na <- Reduce(`&`, lapply(args, is.na))
  res[all_na] <- NA_real_
  res
}

sas_max <- function(...) {
  args <- list(...)
  if (length(args) == 0L) return(numeric(0))
  if (length(args) == 1L) return(args[[1]])
  res <- do.call(pmax, c(args, list(na.rm = TRUE)))
  all_na <- Reduce(`&`, lapply(args, is.na))
  res[all_na] <- NA_real_
  res
}

sas_length <- function(x) {
  if (is.character(x)) {
    s <- sub("\\s+$", "", x)
    ifelse(is.na(s) | s == "", 1L, nchar(s))
  } else {
    ifelse(is.na(x), 1L, nchar(as.character(x)))
  }
}

sas_put <- function(x, fmt) apply_format(x, fmt)

# NOTE: NODUPKEY dedups adjacent sorted keys; distinct() semantics match only after sorting -- which this pipeline guarantees.
sas_sort <- function(df, by, descending = character(), ...) {
  if (nrow(df) == 0L) return(df)
  cols <- lapply(by, function(v) {
    idx <- match(tolower(v), tolower(names(df)))
    if (is.na(idx)) {
      stop("sas_sort: by variable not found in dataset: ", v, call. = FALSE)
    }
    x <- df[[idx]]
    desc <- tolower(v) %in% tolower(descending)
    if (desc) {
      rank(-xtfrm(x), na.last = TRUE, ties.method = "min")
    } else {
      rank(xtfrm(x), na.last = FALSE, ties.method = "min")
    }
  })
  ord <- do.call(order, c(cols, list(method = "radix")))
  df[ord, , drop = FALSE]
}

sas_merge <- function(a, b, by,
                      keep = c("both", "left", "right", "left_only",
                               "right_only", "full"), ...) {
  keep <- match.arg(keep)
  dup_a <- anyDuplicated(a[by]) > 0L
  dup_b <- anyDuplicated(b[by]) > 0L
  if (dup_a && dup_b)
    stop("sas_merge: many-to-many merge on keys (", paste(by, collapse = ", "),
         ") -- SAS row-walking semantics cannot be reproduced by a join. ",
         "This unit requires the PDV-faithful path.", call. = FALSE)
  a_cols <- names(a); b_cols <- names(b)
  a$.in_a <- TRUE; b$.in_b <- TRUE
  m <- merge(a, b, by = by, all = TRUE, suffixes = c(".sas2r_a", ""))
  # SAS overlap rule: the later dataset's value wins where both contribute
  for (v in setdiff(intersect(names(a), names(b)), c(by, ".in_a", ".in_b"))) {
    left <- m[[paste0(v, ".sas2r_a")]]
    miss <- is.na(m$.in_b)
    if (any(miss)) m[[v]][miss] <- left[miss]
    m[[paste0(v, ".sas2r_a")]] <- NULL
  }
  ina <- !is.na(m$.in_a); inb <- !is.na(m$.in_b)
  rows <- switch(keep, both = ina & inb, left = ina, right = inb,
                 left_only = ina & !inb, right_only = inb & !ina, full = ina | inb)
  m <- m[rows, , drop = FALSE]
  m$.in_a <- NULL; m$.in_b <- NULL
  # SAS output shape, not base::merge's: columns follow the contributing
  # datasets in statement order, and rows follow the BY ordering under SAS
  # collation (missing lowest, stable), which sas_sort already implements.
  m <- m[, c(a_cols, setdiff(b_cols, a_cols)), drop = FALSE]
  sas_sort(m, by = by)
}

# ifelse() strips attributes, so a Date or labelled column through an
# IF/THEN assignment came back bare numeric. Selection here starts from the
# branch that carries the column's class. A missing condition is false in SAS.
sas_if_else <- function(cond, yes, no) {
  n <- max(length(cond), length(yes), length(no))
  cond <- rep_len(cond, n)
  idx <- !is.na(cond) & cond
  if (length(no) == 1L && is.logical(no) && is.na(no)) {
    # New-variable form: the false branch is bare NA, so the yes branch is the
    # only carrier of class information.
    out <- rep_len(yes, n)
    out[!idx] <- NA
    return(out)
  }
  yes <- rep_len(yes, n)
  out <- rep_len(no, n)
  out[idx] <- yes[idx]
  out
}

apply_format <- function(x, fmt) {
  if (is.null(fmt)) return(as.character(x))
  fmt_key <- function(v) {
    if (is.na(v)) NA_character_
    else if (is.numeric(v)) format(v, scientific = FALSE, trim = TRUE)
    else as.character(v)
  }
  key <- if (is.numeric(x)) vapply(x, fmt_key, character(1)) else as.character(x)
  out <- if (!is.null(fmt$other)) rep(fmt$other, length(x)) else key
  hit <- !is.na(x) & key %in% names(fmt$values)
  out[hit] <- unname(fmt$values[key[hit]])
  if (!is.null(fmt$ranges)) {
    for (r in fmt$ranges) {
      inr <- !is.na(x) & x >= r$lo & x <= r$hi & !hit
      out[inr] <- r$label
    }
  }
  out[is.na(x) & is.null(fmt$other)] <- NA_character_
  out
}

# %INCLUDE support. Each included SAS file is translated once into its own
# staged module; this executes that module at one include site, into the
# calling program's own environment, exactly where the %INCLUDE stood.
#
# The path is always relative to the staged bundle root -- the nearest ancestor
# of the running script holding _sas2r_registry.R -- and never to the working
# directory, so the bundle can be run from anywhere. Absolute paths and "." or
# ".." components are rejected, and the file the joined path actually resolves
# to is then required to lie under the root: rejecting the components alone
# would still let a symlinked directory inside the bundle read outside it, so
# the confinement is checked on the resolved path, where a hand-edited bundle
# cannot talk its way out.
sas2r_source_include <- function(relative_path, envir = parent.frame()) {
  fail <- function(cls, msg) {
    stop(structure(
      class = c(cls, "sas2r_include_error", "error", "condition"),
      list(message = paste0("sas2r_source_include: ", msg), call = NULL)
    ))
  }
  if (!is.character(relative_path) || length(relative_path) != 1L ||
      is.na(relative_path) || !nzchar(relative_path)) {
    fail("sas2r_include_path_error",
         "relative_path must be one non-empty string")
  }
  if (!is.environment(envir)) {
    fail("sas2r_include_envir_error", "envir must be an environment")
  }
  path <- gsub("\\\\", "/", relative_path)
  parts <- strsplit(path, "/", fixed = TRUE)[[1]]
  if (grepl("^(/|[A-Za-z]:/|//)", path) || !length(parts) ||
      any(!nzchar(parts)) || any(parts %in% c(".", ".."))) {
    fail("sas2r_include_path_error",
         paste0("unsafe staged include path: ", relative_path))
  }

  # Where the file now being sourced lives. source() and sys.source() each keep
  # the path in a frame variable, so the innermost of those frames names the
  # staged file that reached this call -- including a module that was itself
  # reached through an include. A driver started some other way (Rscript, say)
  # has no such frame, and the working directory is the documented fallback.
  start <- NULL
  frames <- sys.frames()
  for (i in rev(seq_along(frames))) {
    fn <- tryCatch(sys.function(i), error = function(e) NULL)
    slot <- if (identical(fn, base::sys.source)) "file" else
            if (identical(fn, base::source)) "ofile" else NULL
    if (is.null(slot)) next
    found <- tryCatch(get(slot, envir = frames[[i]], inherits = FALSE),
                      error = function(e) NULL)
    if (is.character(found) && length(found) == 1L && !is.na(found) &&
        nzchar(found)) {
      start <- dirname(found)
      break
    }
  }
  if (is.null(start)) start <- getwd()

  # Bounded walk upward: it stops at the filesystem root (where dirname() is a
  # fixed point) and after a fixed number of levels, so a bundle with no
  # registry fails with this error instead of looping.
  dir <- normalizePath(start, winslash = "/", mustWork = FALSE)
  root <- NULL
  for (level in seq_len(64L)) {
    if (file.exists(file.path(dir, "_sas2r_registry.R"))) {
      root <- dir
      break
    }
    parent <- dirname(dir)
    if (identical(parent, dir)) break
    dir <- parent
  }
  if (is.null(root)) {
    fail("sas2r_include_root_error",
         paste0("no staged bundle root (_sas2r_registry.R) at or above ", start))
  }

  target <- file.path(root, path)
  if (!file.exists(target) || dir.exists(target)) {
    fail("sas2r_include_missing_error",
         paste0("staged include module not found: ", path))
  }
  # Re-confine after resolution: every component was ..-free, but a symlinked
  # directory inside the bundle resolves outside it all the same.
  real <- normalizePath(target, winslash = "/", mustWork = FALSE)
  real_root <- normalizePath(root, winslash = "/", mustWork = FALSE)
  if (!startsWith(real, paste0(real_root, "/"))) {
    fail("sas2r_include_path_error",
         paste0("staged include module resolves outside the bundle: ", path))
  }
  sys.source(real, envir = envir)
  invisible(real)
}

# Point-of-use libref bindings. The registry this bundle starts with is only a
# seed -- the libraries configuration declares, plus `work`. Every LIBNAME the
# SAS program executes changes the registry where that statement stood, so a
# libref that is rebound or cleared part-way through behaves at run time the
# way it does in SAS, instead of every reference in the program sharing one
# project-wide answer.
sas2r_libname_assign <- function(libref, read_path, write_path = read_path,
                                 engine = "sas7bdat", write = "rds") {
  key <- tolower(libref)
  .sas2r_registry[[key]] <<- list(
    read_path = read_path,
    write_path = write_path,
    engine = engine,
    write = write
  )
  invisible(.sas2r_registry[[key]])
}

sas2r_libname_clear <- function(libref) {
  .sas2r_registry[[tolower(libref)]] <<- NULL
  invisible(NULL)
}

sas2r_libref_stop <- function(cls, msg) {
  stop(structure(
    class = c(cls, "sas2r_libref_error", "error", "condition"),
    list(message = msg, call = NULL)
  ))
}

# The library a libref names is chosen from SAS source or from configuration
# and is deliberately *not* held inside the project -- a study library lives
# where the study keeps it. The confinement that does apply is this one: a
# member is a SAS dataset name, never a path, so the file it resolves to has to
# sit in the library directory itself and cannot walk out of it.
sas2r_lib_entry <- function(libref) {
  reg <- .sas2r_registry[[tolower(libref)]]
  if (is.null(reg)) {
    sas2r_libref_stop("sas2r_unknown_libref",
                      paste0("Unknown libref: ", libref))
  }
  reg
}

sas2r_lib_member_path <- function(dir, member, ext) {
  if (!is.character(member) || length(member) != 1L || is.na(member) ||
      !nzchar(member) || grepl("[/\\\\]", member) ||
      member %in% c(".", "..")) {
    sas2r_libref_stop("sas2r_libref_member_error",
                      paste0("Unsafe dataset member name: ", member))
  }
  file.path(dir, paste0(member, ext))
}

# SAS resolves variable names case-insensitively; R does not. Deterministic
# pipelines fold every frame to lowercase names at entry so lowercase source
# references (`aval`) find uppercase data columns (`AVAL`) the way SAS would.
sas2r_fold_names <- function(df) {
  names(df) <- tolower(names(df))
  df
}

`$.sas2r_dataset` <- function(x, name) {
  idx <- match(tolower(name), tolower(names(x)))
  if (!is.na(idx)) x[[idx]] else NULL
}

`[[.sas2r_dataset` <- function(x, i, exact = TRUE) {
  if (is.character(i) && length(i) == 1L) {
    idx <- match(tolower(i), tolower(names(x)))
    if (!is.na(idx)) return(x[[idx]])
  }
  NextMethod()
}

split_ds <- function(ds, macro_vars = character()) {
  if (length(macro_vars) > 0L && is.character(ds) && length(ds) == 1L) {
    for (nm in names(macro_vars)) {
      if (nzchar(nm)) {
        ds <- gsub(paste0("&", nm, "\\b"), macro_vars[[nm]], ds)
      }
    }
  }
  p <- strsplit(ds, ".", fixed = TRUE)[[1]]
  if (length(p) == 1L) c(lib = "work", member = p[1])
  else c(lib = p[1], member = p[2])
}

lib_read <- function(libref, member = NULL, ...) {
  dots <- list(...)
  if (is.null(member) || missing(member)) {
    if (!is.null(dots$dataset)) {
      member <- dots$dataset
    } else if (!is.null(dots$table)) {
      member <- dots$table
    } else if (!is.null(dots$member)) {
      member <- dots$member
    } else if (grepl(".", libref, fixed = TRUE)) {
      parts <- strsplit(libref, ".", fixed = TRUE)[[1]]
      libref <- parts[1]
      member <- parts[2]
    } else {
      member <- libref
      libref <- "work"
    }
  }
  reg <- sas2r_lib_entry(libref)
  w_dir <- if (!is.null(reg$write_path)) reg$write_path else reg$path
  r_dir <- if (!is.null(reg$read_path)) reg$read_path else reg$path
  find_file <- function(dir) {
    if (is.null(dir) || is.na(dir) || !nzchar(dir)) return(NULL)
    f <- function(ext) sas2r_lib_member_path(dir, member, ext)
    if (file.exists(f(".rds"))) list(type = "rds", path = f(".rds"))
    else if (file.exists(f(".sas7bdat"))) list(type = "sas7bdat", path = f(".sas7bdat"))
    else if (file.exists(f(".xpt"))) list(type = "xpt", path = f(".xpt"))
    else NULL
  }
  target <- find_file(w_dir)
  if (is.null(target)) target <- find_file(r_dir)
  if (is.null(target)) {
    stop("Dataset not found: ", libref, ".", member, call. = FALSE)
  }
  df <- if (target$type == "rds") readRDS(target$path)
  else if (target$type == "sas7bdat") haven::read_sas(target$path)
  else if (target$type == "xpt") haven::read_xpt(target$path)
  class(df) <- unique(c("sas2r_dataset", class(df)))
  df
}

lib_write <- function(df, libref = NULL, member = NULL, ...) {
  dots <- list(...)
  if (is.character(df) && !is.null(libref) && (is.data.frame(libref) || is.list(libref) || is.matrix(libref))) {
    tmp_df <- libref
    libref <- df
    df <- tmp_df
  }
  if (is.null(member) || missing(member)) {
    if (!is.null(dots$dataset)) {
      member <- dots$dataset
    } else if (!is.null(dots$table)) {
      member <- dots$table
    } else if (!is.null(dots$member)) {
      member <- dots$member
    } else if (grepl(".", libref, fixed = TRUE)) {
      parts <- strsplit(libref, ".", fixed = TRUE)[[1]]
      libref <- parts[1]
      member <- parts[2]
    } else {
      member <- libref
      libref <- "work"
    }
  }
  reg <- sas2r_lib_entry(libref)
  w_dir <- if (!is.null(reg$write_path)) reg$write_path else reg$path
  if (is.null(w_dir) || is.na(w_dir) || !nzchar(w_dir)) {
    stop("No writable path configured for libref: ", libref, call. = FALSE)
  }
  dir.create(w_dir, showWarnings = FALSE, recursive = TRUE)
  fmt <- if (is.null(reg$write)) "rds" else reg$write
  if (fmt == "rds") saveRDS(df, sas2r_lib_member_path(w_dir, member, ".rds"))
  else if (fmt == "xpt") haven::write_xpt(df, sas2r_lib_member_path(w_dir, member, ".xpt"))
  else stop("Unsupported write format: ", fmt, call. = FALSE)
  invisible(df)
}

emit_proc_sort <- function(data = NULL, df = NULL, by = character(), descending = character(), ...) {
  target_df <- if (!is.null(data)) data else df
  sas_sort(df = target_df, by = by, descending = descending, ...)
}

sas_display <- function(x) {
  if (is.numeric(x)) {
    out <- character(length(x))
    na_idx <- is.na(x)
    out[na_idx] <- "."
    if (any(!na_idx)) {
      out[!na_idx] <- format(x[!na_idx], trim = TRUE, scientific = FALSE)
    }
  } else {
    out <- as.character(x)
    out[is.na(x)] <- ""
  }
  out
}

