/* Run SAS from the repository root. This exports independent SAS references. */
/* Create tests/testthat/fixtures/semantic-reference/sas-generated first. */
%let corpus=tests/testthat/fixtures/semantic-reference;
%include "&corpus/missing_assignment/setup.sas";
%include "&corpus/missing_assignment/source.sas";
proc export data=out outfile="&corpus/sas-generated/missing_assignment.csv" dbms=csv replace; run;
%include "&corpus/computed_missing/setup.sas";
%include "&corpus/computed_missing/source.sas";
proc export data=out outfile="&corpus/sas-generated/computed_missing.csv" dbms=csv replace; run;
%include "&corpus/where_timing/setup.sas";
%include "&corpus/where_timing/source.sas";
proc export data=out outfile="&corpus/sas-generated/where_timing.csv" dbms=csv replace; run;
%include "&corpus/literal_text/setup.sas";
%include "&corpus/literal_text/source.sas";
proc export data=out outfile="&corpus/sas-generated/literal_text.csv" dbms=csv replace; run;
%include "&corpus/sql_case/setup.sas";
%include "&corpus/sql_case/source.sas";
proc export data=out outfile="&corpus/sas-generated/sql_case.csv" dbms=csv replace; run;
%include "&corpus/sql_group_case/setup.sas";
%include "&corpus/sql_group_case/source.sas";
proc export data=out outfile="&corpus/sas-generated/sql_group_case.csv" dbms=csv replace; run;
%include "&corpus/sql_literal/setup.sas";
%include "&corpus/sql_literal/source.sas";
proc export data=out outfile="&corpus/sas-generated/sql_literal.csv" dbms=csv replace; run;
%include "&corpus/merge_disjoint/setup.sas";
%include "&corpus/merge_disjoint/source.sas";
proc export data=out outfile="&corpus/sas-generated/merge_disjoint.csv" dbms=csv replace; run;
%include "&corpus/merge_shared/setup.sas";
%include "&corpus/merge_shared/source.sas";
proc export data=out outfile="&corpus/sas-generated/merge_shared.csv" dbms=csv replace; run;
%include "&corpus/merge_body/setup.sas";
%include "&corpus/merge_body/source.sas";
proc export data=out outfile="&corpus/sas-generated/merge_body.csv" dbms=csv replace; run;
%include "&corpus/sql_delete/setup.sas";
%include "&corpus/sql_delete/source.sas";
proc export data=out outfile="&corpus/sas-generated/sql_delete.csv" dbms=csv replace; run;
%include "&corpus/sql_update/setup.sas";
%include "&corpus/sql_update/source.sas";
proc export data=out outfile="&corpus/sas-generated/sql_update.csv" dbms=csv replace; run;
%include "&corpus/multiple_where/setup.sas";
%include "&corpus/multiple_where/source.sas";
proc export data=out outfile="&corpus/sas-generated/multiple_where.csv" dbms=csv replace; run;
%include "&corpus/comparison_values/setup.sas";
%include "&corpus/comparison_values/source.sas";
proc export data=out outfile="&corpus/sas-generated/comparison_values.csv" dbms=csv replace; run;
data _null_;
file "&corpus/sas-generated/provenance.txt";
put "SAS &sysvlong on &sysscp; &sysdate9 &systime";
run;
