BANNER <- c(
  "# Generated by sas2r -- DETERMINISTIC TRANSLATION",
  "# NOT VERIFIED AGAINST SAS OUTPUTS -- THIS IS NOT PARITY.",
  "# Review required before any production use."
)

#' The bootstrap header an entry-point module carries
#'
#' A staged program has to enter the registry, helper, and format bootstrap to
#' run at all. One and the same file can be both a program the project lists as
#' an entry point *and* the target of a `%INCLUDE`, and the header has to serve
#' both without a flag telling it which is happening, because both can happen
#' to the same bundle on different days.
#'
#' Two properties make that possible:
#'
#' * **Idempotent.** The bootstrap runs only when `.sas2r_registry` is not
#'   already bound in the environment the module is being evaluated in. Entered
#'   directly, that is a fresh environment and the bootstrap runs; reached
#'   through `sas2r_source_include()`, the including program has already
#'   bootstrapped *that same environment*, so it is skipped. Nothing is sourced
#'   twice, and a caller that supplied its own registry or helpers keeps them.
#'   The guard checks only for the registry, so a caller that pre-binds
#'   `.sas2r_registry` without also pre-binding the helpers gets neither, and
#'   the module fails on its first `lib_read()`.
#' * **Anchored on the module, not on the working directory.** The bundle root
#'   is found by walking up from the file being sourced -- the same search
#'   `sas2r_source_include()` performs -- so a module in a subdirectory, or one
#'   run from anywhere other than the bundle root, still finds the bundle. The
#'   previous `source("_sas2r_registry.R")` form silently depended on
#'   `getwd()`.
#'
#' Everything is sourced with `local = environment()`, which is the module's own
#' evaluation environment. A driver sourced into a sandbox therefore keeps its
#' registry, `lib_read()`, and `sas2r_source_include()` inside that sandbox
#' rather than leaking them into `globalenv()`.
#'
#' The bundle-root walk is duplicated here rather than called from
#' `sas2r-helpers.R`, because it has to run *before* the helpers are loaded.
#'
#' @return A character vector of R source lines.
#' @noRd
module_bootstrap <- function() {
  c(
    "# sas2r bootstrap -- idempotent, and anchored on this module's own",
    "# directory rather than the working directory. Entered directly, this file",
    "# loads the registry, helpers, and formats; reached from an %INCLUDE call",
    "# site, it finds them already loaded in the environment it is running in",
    "# and loads nothing. A file that is both an entry point and an include",
    "# target therefore works either way, and leaks nothing either way.",
    'if (!exists(".sas2r_registry", envir = environment(), inherits = FALSE)) {',
    "  .sas2r_boot_root <- local({",
    "    frames <- sys.frames()",
    "    start <- NULL",
    "    for (i in rev(seq_along(frames))) {",
    "      fn <- tryCatch(sys.function(i), error = function(e) NULL)",
    '      slot <- if (identical(fn, base::sys.source)) "file"',
    '              else if (identical(fn, base::source)) "ofile" else NULL',
    "      if (is.null(slot)) next",
    "      f <- tryCatch(get(slot, envir = frames[[i]], inherits = FALSE),",
    "                    error = function(e) NULL)",
    "      if (is.character(f) && length(f) == 1L && !is.na(f) && nzchar(f)) {",
    "        start <- dirname(f)",
    "        break",
    "      }",
    "    }",
    "    if (is.null(start)) start <- getwd()",
    '    dir <- normalizePath(start, winslash = "/", mustWork = FALSE)',
    "    root <- NULL",
    "    for (level in seq_len(64L)) {",
    sprintf("      if (file.exists(file.path(dir, %s))) {",
            deparse(SAS2R_BUNDLE_FILES[1])),
    "        root <- dir",
    "        break",
    "      }",
    "      parent <- dirname(dir)",
    "      if (identical(parent, dir)) break",
    "      dir <- parent",
    "    }",
    "    if (is.null(root)) {",
    '      stop("sas2r bootstrap: no staged bundle root (_sas2r_registry.R) at ",',
    '           "or above ", start, call. = FALSE)',
    "    }",
    "    root",
    "  })",
    sprintf("  for (.sas2r_boot_file in c(%s)) {",
            paste(vapply(SAS2R_BUNDLE_FILES, deparse, character(1)),
                  collapse = ", ")),
    "    source(file.path(.sas2r_boot_root, .sas2r_boot_file), local = environment())",
    "  }",
    '  rm(list = c(".sas2r_boot_root", ".sas2r_boot_file"),',
    "     envir = environment())",
    "}"
  )
}

stub_block <- function(unit_stmts, reason, unit_id = NULL) {
  hdr <- if (is.null(unit_id)) sprintf("# sas2r:untranslated reason=%s", reason)
         else sprintf("# sas2r:untranslated unit=%d reason=%s", as.integer(unit_id), reason)
  sas_text <- format_sas_statements(unit_stmts$text)
  c(hdr,
    "# --- original SAS ---",
    paste0("# ", unlist(strsplit(sas_text, "\n"))),
    "# --------------------")
}

dispatch_proc <- function(us, rb) {
  proc <- tolower(sub("^proc\\s+(\\w+).*$", "\\1",
                      us$text[us$first_token == "proc"][1], ignore.case = TRUE))
  entry <- rb$procs[[proc]]
  if (is.null(entry)) return(list(em = NULL, reason = paste0("proc_unknown:", proc)))
  if (is.null(entry$emitter))
    return(list(em = NULL, reason = paste0("proc_", entry$status, ":", proc)))
  fn <- get(entry$emitter, envir = asNamespace("sas2r"), mode = "function")
  em <- fn(us)
  if (is.na(em$code[1])) return(list(em = NULL, reason = em$flags[1]))
  list(em = em, reason = NULL)
}

#' Every scanned file that becomes a staged R module, with its module path
#'
#' Program files keep the staged path they have always had. Each *resolved*
#' included file becomes one module of its own, whatever number of `%INCLUDE`
#' sites reach it, named by [canonical_include_staged_path()] so that two
#' out-of-root includes sharing a basename cannot collide.
#'
#' Environment (`autoexec`) files are deliberately absent, exactly as before:
#' this task changed what included source gets translated, not what the
#' environment contributes.
#'
#' A file the scanner read but that has since disappeared cannot be
#' canonicalized, so it is dropped here rather than aborting the run; the
#' occurrences pointing at it stub with `include_not_staged`.
#'
#' @param project A `sas2r_project` object.
#' @return A tibble of `file`, `staged_file`, and `origin`, one row per module.
#' @noRd
transpile_staged_modules <- function(project) {
  empty <- tibble::tibble(file = character(), staged_file = character(),
                          origin = character())
  files <- project$files
  if (is.null(files) || !nrow(files)) return(empty)
  files <- files[files$origin %in% c("program", "included"), , drop = FALSE]
  if (!nrow(files)) return(empty)

  staged <- vapply(seq_len(nrow(files)), function(k) {
    if (identical(files$origin[k], "program")) {
      canonical_rel_staged_path(files$file[k], project_dir = project$project_dir)
    } else if (file.exists(files$file[k])) {
      canonical_include_staged_path(files$file[k], project$project_dir)
    } else {
      NA_character_
    }
  }, character(1))

  ok <- !is.na(staged) & nzchar(staged)
  out <- tibble::tibble(file = files$file[ok], staged_file = staged[ok],
                        origin = files$origin[ok])
  # Two source files sharing one module path would silently overwrite each
  # other's translation, so the collision is refused rather than resolved.
  dup <- unique(out$staged_file[duplicated(out$staged_file)])
  if (length(dup)) {
    cli::cli_abort(
      c("Two source files stage to the same R module.",
        "x" = "Colliding module{?s}: {.file {dup}}."),
      class = "sas2r_staged_path_collision"
    )
  }
  out
}

#' Units whose `%INCLUDE` sites can become calls where they stand
#'
#' A `%INCLUDE` inside a macro definition or a DATA- or PROC-step body cannot
#' be replaced by a call at the point it stands: the surrounding unit is
#' translated as a whole, or not at all, and there is no place in the emitted
#' form for a statement that runs mid-step. Only a unit that *is* the
#' `%INCLUDE` -- one at global scope, which [sas_units()] gives a unit of its
#' own -- emits.
#'
#' This is the single definition of that condition; [transpile_source_file()]
#' dispatches on it and [sas_transpile()] uses it to find the modules no call
#' reaches. Deriving both from one predicate is what keeps the emitted bundle
#' and the manifest from disagreeing about which modules are live.
#'
#' @param project A `sas2r_project` object.
#' @return An integer vector of unit ids.
#' @noRd
include_emitting_units <- function(project) {
  st <- project$statements
  if (is.null(st) || !nrow(st)) return(integer())
  firsts <- st[!duplicated(st$unit_id), , drop = FALSE]
  ok <- !(firsts$unit_type %in% c("data_step", "proc_step", "macro_def")) &
    tolower(firsts$first_token) == "%include"
  as.integer(firsts$unit_id[ok])
}

#' Decide, per parent unit, what each `%INCLUDE` site emits
#'
#' Only a `resolved` occurrence has a scanned file behind it. `cycle` and
#' `depth_exceeded` occurrences carry a non-`NA` `target_file` for a file the
#' scanner deliberately never read, so resolution status -- never the presence
#' of a target path -- decides whether a call may be emitted. Every other
#' status keeps its own scanner reason and stays a stub.
#'
#' Each site is decided on its own. An earlier version stopped at the first
#' unemittable site and discarded the calls already accumulated, so a unit
#' holding `[resolved, cycle]` lost the resolved call as well; a unit with
#' mixed statuses now emits every call it can and reports the first reason it
#' could not.
#'
#' @param project A `sas2r_project` object.
#' @param modules The module table from [transpile_staged_modules()].
#' @return A list keyed by parent unit id. Each entry carries `calls` (the call
#'   lines, in source order), `modules` (the staged modules those calls reach),
#'   `reason` (the first site that could not be emitted, or `NA`), and
#'   `markers` (one marked comment per site, for a parent unit that emits no
#'   call at all and so keeps none of `calls`).
#' @noRd
include_emission_plan <- function(project, modules) {
  plan <- list()
  occ <- project$include_graph$occurrences
  if (is.null(occ) || !nrow(occ)) return(plan)
  paths <- stats::setNames(as.list(modules$staged_file),
                           include_scan_key(modules$file))
  # Several sites can share one unit, so they are emitted in source order.
  occ <- occ[order(as.integer(occ$parent_unit_id), as.integer(occ$line),
                   seq_len(nrow(occ))), , drop = FALSE]
  for (uid in unique(as.integer(occ$parent_unit_id))) {
    sites <- occ[as.integer(occ$parent_unit_id) == uid, , drop = FALSE]
    calls <- character()
    reached <- character()
    markers <- character()
    reason <- NA_character_
    for (k in seq_len(nrow(sites))) {
      site_reason <- NA_character_
      module <- NULL
      if (!identical(sites$status[k], "resolved")) {
        site_reason <- sites$reason[k]
        if (is.na(site_reason) || !nzchar(site_reason)) {
          site_reason <- paste0("include_", sites$status[k])
        }
      } else {
        target <- sites$target_file[k]
        module <- if (is.na(target) || !nzchar(target)) NULL else
          paths[[include_scan_key(target)]]
        if (is.null(module) || is.na(module)) {
          site_reason <- "include_not_staged"
          module <- NULL
        }
      }
      marker_reason <- if (is.na(site_reason)) "include_site_not_emitted"
                       else site_reason
      markers <- c(markers,
                   sprintf("# sas2r:untranslated include line=%s reason=%s",
                           sites$line[k], marker_reason))
      if (is.na(site_reason)) {
        calls <- c(calls, emit_include_call(module))
        reached <- c(reached, module)
      } else {
        calls <- c(calls, markers[length(markers)])
        if (is.na(reason)) reason <- site_reason
      }
    }
    plan[[as.character(uid)]] <- list(calls = calls, modules = unique(reached),
                                      reason = reason, markers = markers)
  }
  plan
}

#' Staged modules no emitted call reaches, and those only a dead one does
#'
#' A resolved `%INCLUDE` target is staged as a module that runs only where a
#' call to it was emitted. When every site reaching it sits inside a unit that
#' cannot emit, the module is unreachable: it would otherwise arrive in the
#' manifest as ordinary translated code, be bound to an approval identity, and
#' be approved as a translation that can never run.
#'
#' A file the project independently lists as a program is never demoted,
#' however it is also reached. The project's own entry-point list is the
#' statement that the file is run directly -- in a directory project the glob
#' *is* that list -- and stubbing it would throw away correct deterministic
#' translation, take its units out of the agent queue, and print a banner
#' claiming nothing runs the file when the user runs it themselves. Its parent
#' unit still carries `include_site_not_emitted` where the dropped site stands.
#'
#' Reachability is transitive, and is therefore computed to a fixed point. A
#' global `%INCLUDE` inside a module that is itself unreachable is not a live
#' site: the unit holding it is stubbed along with the rest of its module, so
#' the call is never emitted and the target it names is unreachable in turn. A
#' single pass over every emitting unit missed that, and staged the deeper
#' module as clean `t1` translation nothing executes -- approvable dead code.
#'
#' A unit in a file that has no staged module at all -- an `autoexec`, which
#' contributes environment rather than translation and is deliberately never
#' staged -- is left counting as a live site, exactly as before: demoting its
#' target would take correct deterministic translation away from a shape this
#' task never covers. That target is real, complete `t1` translation, but no
#' file anywhere in the bundle holds a call that runs it either, so it has to
#' be told apart from a genuinely-called module. Reachability is therefore
#' computed twice to the same fixed point -- once letting such a unit count as
#' live regardless, once not. A module only the first walk reaches is neither
#' unreachable (so it is not stubbed) nor actually called by anything staged
#' (so it is not ordinary, either); it comes back as `unstaged_parent`, for
#' [transpile_source_file()]'s argument of the same name to flag rather than
#' stub.
#'
#' @param project A `sas2r_project` object.
#' @param modules The module table from [transpile_staged_modules()].
#' @param plan The plan from [include_emission_plan()].
#' @param targets Scan keys of every resolved `%INCLUDE` target, from
#'   [include_resolved_targets()].
#' @return A list with `orphan` and `unstaged_parent`, each a character vector
#'   of staged module paths, possibly empty.
#' @noRd
include_module_reachability <- function(project, modules, plan,
                                        targets = include_resolved_targets(project)) {
  empty <- list(orphan = character(), unstaged_parent = character())
  if (!length(targets) || !nrow(modules)) return(empty)
  keys <- include_scan_key(modules$file)
  # An entry point is live by definition, so it is never a candidate and always
  # seeds both walks below.
  candidate <- keys %in% targets & !(modules$origin %in% "program")
  if (!any(candidate)) return(empty)

  st <- project$statements
  firsts <- st[!duplicated(st$unit_id), , drop = FALSE]
  unit_module <- stats::setNames(
    modules$staged_file[match(include_scan_key(firsts$file), keys)],
    as.character(as.integer(firsts$unit_id)))
  emitting <- as.character(include_emitting_units(project))
  seed <- modules$staged_file[!candidate]

  # `unstaged_parent_is_live`: whether a unit whose own file has no staged
  # module (an autoexec) counts as live regardless of what reaches it, which
  # is the one difference between the two walks.
  reach <- function(unstaged_parent_is_live) {
    live <- seed
    repeat {
      from <- unname(unit_module[emitting])
      live_units <- if (unstaged_parent_is_live) {
        emitting[is.na(from) | from %in% live]
      } else {
        emitting[!is.na(from) & from %in% live]
      }
      reached <- unlist(lapply(plan[intersect(names(plan), live_units)],
                               `[[`, "modules"), use.names = FALSE)
      fresh <- setdiff(reached %||% character(), live)
      if (!length(fresh)) break
      live <- c(live, fresh)
    }
    live
  }

  live_with_bypass <- reach(TRUE)
  live_strict <- reach(FALSE)
  cand_paths <- modules$staged_file[candidate]
  list(orphan = setdiff(cand_paths, live_with_bypass),
       unstaged_parent = intersect(cand_paths,
                                   setdiff(live_with_bypass, live_strict)))
}

#' Scan keys of every file a resolved `%INCLUDE` names
#' @param project A `sas2r_project` object.
#' @return A character vector of scan keys, possibly empty.
#' @noRd
include_resolved_targets <- function(project) {
  occ <- project$include_graph$occurrences
  if (is.null(occ) || !nrow(occ)) return(character())
  tgt <- occ$target_file[occ$status == "resolved"]
  tgt <- tgt[!is.na(tgt) & nzchar(tgt)]
  if (!length(tgt)) return(character())
  unique(include_scan_key(tgt))
}

#' Canonical absolute path of a file that need not exist yet
#'
#' `normalizePath()` resolves a path only as far as the filesystem can answer
#' for it: given a file that has not been written yet it returns the argument
#' untouched, symlinked parent directories and all. Comparing such a path
#' against a canonicalized source path is a comparison between two different
#' coordinate systems. This resolves the deepest ancestor that does exist and
#' re-joins the components below it, so an output path is named the same way a
#' source path is.
#'
#' @param path A single path.
#' @return The canonical absolute path, forward-slash separated.
#' @noRd
canonical_output_path <- function(path) {
  cur <- gsub("\\\\", "/", path)
  tail <- character()
  while (!file.exists(cur)) {
    parent <- dirname(cur)
    if (identical(parent, cur)) break
    tail <- c(basename(cur), tail)
    cur <- parent
  }
  base <- sub("/+$", "", include_normalize_path(cur))
  if (!length(tail)) return(if (nzchar(base)) base else "/")
  paste(c(base, tail), collapse = "/")
}

#' Refuse to write a generated file over a scanned source file
#'
#' Staged module paths are checked against each other in
#' [transpile_staged_modules()], but never against the source files they were
#' derived from. Transpiling in place -- `out_dir` at or inside the project
#' root -- then lets a module whose name survived from its target overwrite the
#' user's own SAS with generated R. The naming rule in
#' [staged_r_module_path()] keeps that from arising today; this guard is what
#' keeps a future change to that rule from destroying source in silence.
#'
#' The three fixed-name bundle files are guarded on the same footing. Their
#' names cannot be renamed out of the way of a source that happens to share
#' one, and they are written first, so a source named `sas2r-helpers.R` was
#' destroyed before any module-path check could fire -- as were the same three
#' files in a user's source directory whenever a *module* collision aborted the
#' run. This runs before anything at all is written, so an abort leaves the
#' output directory exactly as it found it.
#'
#' @param project A `sas2r_project` object.
#' @param modules The module table from [transpile_staged_modules()].
#' @param out_dir Output directory path; it must already exist.
#' @return `NULL`, invisibly. Aborts on a collision.
#' @noRd
guard_staged_paths_against_sources <- function(project, modules, out_dir) {
  src <- project$files$file
  src <- src[!is.na(src) & nzchar(src) & file.exists(src)]
  if (!length(src)) return(invisible(NULL))
  root <- normalizePath(out_dir, winslash = "/", mustWork = TRUE)
  written <- c(modules$staged_file, SAS2R_BUNDLE_FILES)
  written_keys <- tolower(vapply(file.path(root, gsub("\\\\", "/", written)),
                                 canonical_output_path, character(1),
                                 USE.NAMES = FALSE))
  hit <- include_scan_key(src) %in% written_keys
  if (any(hit)) {
    cli::cli_abort(
      c("A file sas2r generates would be written over a scanned source file.",
        "x" = "Source{?s} at risk: {.file {src[hit]}}.",
        "i" = "Choose an {.arg out_dir} outside the project, or rename the source."),
      class = "sas2r_staged_path_overwrites_source"
    )
  }
  invisible(NULL)
}

#' Emit the registry change every `LIBNAME` statement of one unit makes
#'
#' A global `LIBNAME` is a unit of its own, so this ordinarily emits one line.
#' It is still written over *every* statement the unit contributed, in source
#' order, so a unit that ever held two `LIBNAME`s emits both instead of silently
#' dropping the second. `unit_id` alone identifies the unit because
#' `sas_project()` numbers units across the whole project, not per file.
#'
#' Two kinds of statement reach it. A binding row from the projection emits the
#' registry change the project selected; a `LIBNAME` naming `work` binds
#' nothing at all -- see [emit_session_library_statement()] -- and emits only a
#' marker. Both are ordered by source line together, so a unit holding one of
#' each still reads in the order the SAS was written.
#'
#' @param effective The projection from [effective_librefs()].
#' @param unit_id The unit being translated.
#' @return A character vector of R source lines, possibly empty.
#' @noRd
emit_libref_unit <- function(effective, unit_id) {
  uid <- as.integer(unit_id)
  b <- effective$bindings
  keep <- which(b$kind == "statement" & !is.na(b$unit_id) & b$unit_id == uid)
  s <- effective$session_library %||% empty_session_library()
  skeep <- which(!is.na(s$unit_id) & s$unit_id == uid)
  if (!length(keep) && !length(skeep)) return(character())
  order_by <- c(b$use_line[keep], s$use_line[skeep])
  emitters <- c(
    lapply(keep, function(k) {
      function() emit_libref_statement(b[k, ], effective$seed)
    }),
    lapply(skeep, function(k) function() emit_session_library_statement(s[k, ]))
  )
  emitters <- emitters[order(order_by, seq_along(order_by))]
  unlist(lapply(emitters, function(f) f()), use.names = FALSE)
}

#' Refuse to emit a read or write whose libref has no single binding
#'
#' A libref that resolves to different libraries in different execution
#' contexts has no answer a staged module could carry: the module is one file
#' per source file, and it would have to name one library for every program
#' that runs it. The plan's rule is to fail rather than to pick, and to fail
#' *here* -- at transpile time, where the user can still name the context --
#' rather than to emit a bundle that reads whichever library the ambient
#' registry happens to hold.
#'
#' The check is per emitting unit, so a project that merely *contains* an
#' ambiguous libref still translates everything else: only a unit that would
#' really generate the read or write is refused.
#'
#' **It aborts mid-emission, and that leaves a partial bundle.** Which units
#' emit is only known by translating them, so the check cannot run before
#' anything is written the way [guard_staged_paths_against_sources()] does. By
#' the time it fires, the registry, helpers, and formats are written and the
#' modules before this one are too. No source file is at risk -- staged paths
#' are guarded against source paths before any write -- but re-running into an
#' `out_dir` that already held a good bundle leaves a *new* registry beside
#' *stale* modules, a combination that parses, runs, and can read the wrong
#' library. Clear `out_dir` after a failed transpile; see [sas_transpile()].
#'
#' @param project A `sas2r_project` object.
#' @param unit_id The unit that emitted.
#' @param file The source file it came from.
#' @return `NULL`, invisibly. Aborts on ambiguity.
#' @noRd
guard_unit_bindings <- function(project, unit_id, file) {
  lineage <- project$lineage
  status <- lineage[["binding_status"]]
  if (is.null(status)) return(invisible(NULL))
  hit <- lineage$unit_id == unit_id & !is.na(status) &
    status == "ambiguous_libref"
  # `lineage$unit_id` is NA on a row whose unit could not be attributed, so
  # `hit` can hold NA and `any(hit)` can be NA. Without `na.rm` the guard then
  # raised "missing value where TRUE/FALSE needed" instead of either passing
  # the unit or refusing it. A row that names no unit is not this unit's.
  if (!any(hit, na.rm = TRUE)) return(invisible(NULL))
  hit <- !is.na(hit) & hit
  datasets <- unique(lineage$dataset[hit])
  cli::cli_abort(
    c("A generated read or write needs a libref with more than one plausible binding.",
      "x" = "Unit {.val {unit_id}} of {.file {file}} uses {.val {datasets}}.",
      "i" = "Two execution contexts bind that libref to different libraries; give each program its own {.code LIBNAME} or name the library in {.field libraries}."),
    class = "sas2r_ambiguous_libref"
  )
}

#' Translate one scanned SAS file into one staged R module
#'
#' The same dispatch serves program files and included modules, so an included
#' unit reaches the manifest with the same `tier`, `dataset`, `code`, lint, and
#' staged-file fields a top-level unit would.
#'
#' @param project A `sas2r_project` object.
#' @param file Path of the scanned SAS file.
#' @param staged_file Relative path of the module to write.
#' @param out_dir Output directory path.
#' @param rulebook Loaded PROC rulebook.
#' @param include_plan Per-unit include decisions from [include_emission_plan()].
#' @param bootstrap Whether the module carries the header from
#'   [module_bootstrap()]. A file the project lists as an entry point does,
#'   whether or not a `%INCLUDE` also names it; a file reached only through a
#'   `%INCLUDE` runs inside the environment of the program that included it and
#'   has no standalone entry to bootstrap for.
#' @param emit_units Unit ids whose `%INCLUDE` sites become calls, from
#'   [include_emitting_units()].
#' @param orphan Whether no emitted call reaches this module, in which case
#'   every unit in it is stubbed rather than presented as live translation.
#' @param unstaged_parent Whether this module is reached only through a
#'   `%INCLUDE` site whose own file has no staged module (an autoexec).
#'   Translation stays complete and `t1` -- it is not `orphan` -- but every row
#'   carries the `include_parent_not_staged` advisory flag, and the header
#'   stops asserting an execution that does not happen: no call to this module
#'   is emitted anywhere in the bundle.
#' @param effective The projection from [effective_librefs()], which supplies
#'   the binding every `LIBNAME` unit emits.
#' @return A list of manifest rows, one per unit of the file.
#' @noRd
transpile_source_file <- function(project, file, staged_file, out_dir, rulebook,
                                  include_plan = list(), bootstrap = TRUE,
                                  emit_units = integer(), orphan = FALSE,
                                  unstaged_parent = FALSE,
                                  effective = effective_librefs(project)) {
  f <- file
  rel_r <- staged_file
  rows <- list()
  out_file <- file.path(out_dir, rel_r)
  dir.create(dirname(out_file), showWarnings = FALSE, recursive = TRUE)

  st_f <- project$statements[project$statements$file == f, ]
  out_chunks <- if (orphan) {
    list(BANNER,
         "# UNREACHABLE MODULE -- no emitted call reaches this file. Every %INCLUDE",
         "# site naming it either sits inside a macro definition or a DATA- or",
         "# PROC-step body, where sas2r cannot emit a call, or sits inside another",
         "# module that is itself unreachable. The project does not list this file as",
         "# a program either, so nothing in the staged bundle executes it and its",
         "# units are left as stubs rather than presented as translation.", "")
  } else if (bootstrap) {
    list(BANNER, "", module_bootstrap(), "")
  } else if (unstaged_parent) {
    list(BANNER,
         "# Included module -- one per included SAS file. Every %INCLUDE site",
         "# reaching it sits in a file with no staged module of its own -- an",
         "# autoexec, which contributes environment rather than translation and is",
         "# never staged -- so no file in this bundle holds a call that runs it. It",
         "# does not enter the registry, helper, and format bootstrap itself.", "")
  } else {
    list(BANNER,
         "# Included module -- one per included SAS file. It is executed at every",
         "# %INCLUDE site, inside the including program's own environment, and so",
         "# does not enter the registry, helper, and format bootstrap itself.", "")
  }
  for (uid in unique(st_f$unit_id)) {
    us <- st_f[st_f$unit_id == uid, ]
    ut <- us$unit_type[1]
    em <- NULL; reason <- NA_character_; ir <- NULL
    first <- tolower(us$first_token[1])

    target_ds <- project$lineage$dataset[project$lineage$role == "creates" & project$lineage$unit_id == uid][1]

    # An unreachable module is stubbed whole -- libname registration included,
    # since nothing in it ever runs -- so the file and the manifest agree that
    # none of it is translation a reviewer could approve.
    if (orphan) {
      out_chunks[[length(out_chunks) + 1L]] <- c(
        sprintf("# --- sas2r:unit %s ---", uid),
        stub_block(us, "include_site_not_emitted", uid), "")
      rows[[length(rows) + 1L]] <- list(
        unit_id = uid, file = f, staged_file = rel_r, unit_type = ut,
        tier = "stub", dataset = target_ds,
        gate_reached = NA_character_, evidence_basis = NA_character_,
        reason = "include_site_not_emitted", flags = "orphan_module",
        code = NA_character_, lint_errors = 0L, lint_warnings = 0L)
      next
    }

    # A LIBNAME is a registry change at the point it stands, so it emits one --
    # built from the binding the project already selected at that statement's
    # own point of use, never from a second reading of the statement text.
    if (first == "libname") {
      code_lines <- emit_libref_unit(effective, uid)
      # A `LIBNAME` shape the scanner does not recognize -- a concatenated
      # library, say -- contributes no statement to the projection and so has
      # no binding to emit. It had none before this unit gained an anchor
      # either, but an anchor with nothing under it reads as "this translated
      # to nothing", so the statement is shown instead of vanishing.
      if (!length(code_lines)) {
        code_lines <- c(
          sprintf("# sas2r:libref_unrecognized unit=%d -- not a LIBNAME form sas2r reads",
                  as.integer(uid)),
          paste0("# ", unlist(strsplit(format_sas_statements(us$text), "\n"))))
      }
      code <- paste(code_lines, collapse = "\n")
      out_chunks[[length(out_chunks) + 1L]] <- c(
        sprintf("# --- sas2r:unit %s ---", uid), code_lines, "")
      rows[[length(rows) + 1L]] <- list(
        unit_id = uid, file = f, staged_file = rel_r, unit_type = ut, tier = "t1",
        dataset = NA_character_, gate_reached = NA_character_, evidence_basis = NA_character_,
        reason = NA_character_, flags = "registry",
        code = code, lint_errors = 0L, lint_warnings = 0L
      )
      next
    }

    tryCatch({
      if (ut == "data_step") {
        ir <- parse_data_step(us)
        if (is.na(target_ds) && length(ir$outputs) > 0L) {
          target_ds <- ir$outputs[1]
        }
        if (nrow(ir$blockers)) {
          reason <- ir$blockers$reason[1]
        } else {
          em <- if (ir$route == "merge") emit_merge_step(ir)
                else emit_data_step(ir, src_file = f)
        }
      } else if (ut == "proc_step") {
        dp <- dispatch_proc(us, rulebook)
        em <- dp$em
        reason <- dp$reason
      } else if (ut == "macro_def") {
        reason <- "macro_deferred"
      } else if (uid %in% emit_units) {
        site <- include_plan[[as.character(uid)]]
        calls <- site$calls %||% character()
        emitted <- grepl("^sas2r_source_include\\(", calls)
        if (any(emitted)) {
          # Every site the unit could emit is kept; a site it could not is left
          # in place as a marked comment, so a mixed unit loses nothing.
          em <- list(code = paste(calls, collapse = "\n"),
                     stmt_map = as.integer(us$stmt_id),
                     flags = if (all(emitted)) character()
                             else "include_site_not_emitted")
        } else {
          reason <- site$reason %||% "include_statement"
        }
      } else {
        reason <- "global_deferred"
      }
    }, sas2r_expr_unmapped_function = function(e) {
      reason <<- paste0("unmapped_function:", e$fname %||% "unknown")
      em <<- NULL
    }, sas2r_expr_parse_error = function(e) {
      reason <<- "expr_parse_failed"
      em <<- NULL
    }, error = function(e) {
      reason <<- "emission_failed"
      em <<- NULL
    })

    # Post-dispatch validation: check if code is NA or empty
    if (!is.null(em) && (is.na(em$code[1]) || !nzchar(trimws(em$code[1])))) {
      reason <- if ("merge_unsupported_shape" %in% em$flags) "merge_unsupported_shape"
                else if (length(em$flags) && nzchar(em$flags[1])) em$flags[1]
                else "emission_failed"
      em <- NULL
    }

    # Lint check on emitted code: if parse error or banned function, fallback to stub
    lint <- NULL
    if (!is.null(em)) {
      lint <- lint_r_code(em$code)
      errs <- lint[lint$level == "error", ]
      if (nrow(errs) > 0L) {
        reason <- paste0("lint_error:", errs$kind[1])
        em <- NULL
      }
    }

    # A unit that holds a %INCLUDE it cannot emit carries a signal either way.
    # Without it a PROC step whose body holds a resolved include reaches the
    # manifest as an unqualified T1 translation with the include silently
    # dropped -- nothing in the row says a statement went missing.
    #
    # The same has to be said in the emitted file, not only in the manifest: a
    # human reading driver.R to approve it sees a clean sas_sort() and no sign
    # that a statement went with it. A mixed *emitting* unit already keeps its
    # dropped sites as marked comments among its calls; a non-emitting parent
    # keeps none of those calls, so its markers are placed here instead.
    # They sit immediately after the unit anchor, which is inside the block
    # locate_unit_block() spans for a t1 unit and for a stub alike, so a later
    # splice replaces them with the unit rather than stranding them beside it.
    extra_flags <- character()
    site_markers <- character()
    if (!(uid %in% emit_units) && !is.null(include_plan[[as.character(uid)]])) {
      extra_flags <- "include_site_not_emitted"
      site_markers <- include_plan[[as.character(uid)]]$markers %||% character()
    }

    if (!is.null(em)) {
      # Refused at transpile time, and only for a unit that actually emitted: a
      # stubbed unit generates no read or write, so it needs no binding and
      # must not lose its stub to someone else's ambiguity.
      guard_unit_bindings(project, uid, f)
      out_chunks[[length(out_chunks) + 1L]] <- c(sprintf("# --- sas2r:unit %s ---", uid), site_markers, em$code, "")
      rows[[length(rows) + 1L]] <- list(
        unit_id = uid, file = f, staged_file = rel_r, unit_type = ut, tier = "t1",
        dataset = target_ds,
        gate_reached = NA_character_,
        evidence_basis = NA_character_,
        reason = NA_character_,
        flags = paste(unique(c(em$flags, extra_flags)), collapse = ","),
        code = em$code,
        lint_errors = sum(lint$level == "error"),
        lint_warnings = sum(lint$level == "warn"))
    } else {
      out_chunks[[length(out_chunks) + 1L]] <- c(sprintf("# --- sas2r:unit %s ---", uid), site_markers, stub_block(us, reason, uid), "")
      rows[[length(rows) + 1L]] <- list(
        unit_id = uid, file = f, staged_file = rel_r, unit_type = ut, tier = "stub",
        dataset = target_ds,
        gate_reached = NA_character_,
        evidence_basis = NA_character_,
        reason = reason, flags = paste(extra_flags, collapse = ","),
        code = NA_character_,
        lint_errors = 0L, lint_warnings = 0L)
    }
  }

  # A module reached only through an unstaged parent is real, complete t1
  # translation with nothing anywhere in the bundle to call it -- every row it
  # contributed carries the advisory, whatever tier that particular row landed
  # on, since the fact being recorded belongs to the module, not the unit.
  if (unstaged_parent && length(rows)) {
    rows <- lapply(rows, function(r) {
      r$flags <- add_flag(r$flags, "include_parent_not_staged")
      r
    })
  }

  writeLines(unlist(out_chunks, use.names = FALSE), out_file)
  rows
}

#' Deterministically transpile every T1-eligible unit of a project
#'
#' Scans and translates all program files, and every file a resolved `%INCLUDE`
#' pulls in, into R files within `out_dir`. Writes runtime helpers, libref
#' registry, and format catalogs. Emits supported T1 units as R code and
#' untranslated units as comment stubs.
#'
#' An included file becomes one staged module however many times it is
#' included, and each `%INCLUDE` site in the including program becomes one call
#' to that module, emitted where the `%INCLUDE` stood.
#'
#' @section Clear `out_dir` after a failed transpile:
#' Emission is not atomic. The bundle's registry, helpers, and format catalogs
#' are written first, then one module at a time, and a translation that aborts
#' part-way -- a libref with more than one plausible binding is the error that
#' can do this -- stops with the files it has already written still in place.
#' No source file is ever at risk: staged paths are checked against every
#' scanned source before anything is written. But an `out_dir` that already
#' held a *good* bundle is then a mixture: a new registry and new helpers
#' beside modules left over from the previous run. That mixture parses and
#' runs, and its stale modules can read the wrong library. Delete `out_dir`, or
#' translate into an empty one, before re-running after a failure.
#'
#' @param project A `sas2r_project` object.
#' @param out_dir Output directory path.
#' @return An object of class `"sas2r_transpilation"` with elements `$manifest`
#'   and `$out_dir`.
#' @noRd
sas_transpile <- function(project, out_dir) {
  dir.create(out_dir, showWarnings = FALSE, recursive = TRUE)
  rb <- load_rulebook()
  rows <- list()

  # Every module path is settled before anything is emitted: an include site
  # can name a file the scanner reached only later, or not through the queue at
  # all when the target is another program. The guard runs before the first
  # write for the same reason -- an abort must not have already replaced part
  # of the user's source tree with generated files.
  modules <- transpile_staged_modules(project)
  guard_staged_paths_against_sources(project, modules, out_dir)

  # One projection of the project's own bindings, built once and read by the
  # registry seed and by every module's LIBNAME units, so the two cannot
  # disagree about which library a libref names.
  effective <- effective_librefs(project)

  write_helpers(out_dir)
  write_registry(project, out_dir, effective)
  fcat <- compile_format_catalog(project)
  write_formats(fcat$catalog, out_dir)

  plan <- include_emission_plan(project, modules)
  emit_units <- include_emitting_units(project)
  targets <- include_resolved_targets(project)
  reachability <- include_module_reachability(project, modules, plan, targets)

  # A file the project lists as an entry point carries the bootstrap, whether
  # or not a %INCLUDE also names it: it can be run directly, so it must work
  # when it is. Being a resolved include target no longer strips the header,
  # because the header itself is idempotent and anchored on the module's own
  # directory -- see module_bootstrap() -- and so is safe to reach twice.
  for (k in seq_len(nrow(modules))) {
    rows <- c(rows, transpile_source_file(
      project = project, file = modules$file[k],
      staged_file = modules$staged_file[k], out_dir = out_dir, rulebook = rb,
      include_plan = plan,
      bootstrap = identical(modules$origin[k], "program"),
      emit_units = emit_units,
      orphan = modules$staged_file[k] %in% reachability$orphan,
      unstaged_parent = modules$staged_file[k] %in% reachability$unstaged_parent,
      effective = effective
    ))
  }

  manifest <- if (length(rows)) {
    tibble::tibble(
      unit_id = as.integer(vapply(rows, `[[`, integer(1), "unit_id")),
      file = as.character(vapply(rows, `[[`, character(1), "file")),
      staged_file = as.character(vapply(rows, function(r) r$staged_file %||% NA_character_, character(1))),
      unit_type = as.character(vapply(rows, `[[`, character(1), "unit_type")),
      tier = as.character(vapply(rows, `[[`, character(1), "tier")),
      dataset = as.character(vapply(rows, function(r) r$dataset %||% NA_character_, character(1))),
      gate_reached = as.character(vapply(rows, function(r) r$gate_reached %||% NA_character_, character(1))),
      evidence_basis = as.character(vapply(rows, function(r) r$evidence_basis %||% NA_character_, character(1))),
      reason = as.character(vapply(rows, function(r) r$reason %||% NA_character_, character(1))),
      flags = as.character(vapply(rows, function(r) r$flags %||% "", character(1))),
      code = as.character(vapply(rows, function(r) r$code %||% NA_character_, character(1))),
      lint_errors = as.integer(vapply(rows, `[[`, integer(1), "lint_errors")),
      lint_warnings = as.integer(vapply(rows, `[[`, integer(1), "lint_warnings")),
      agent_review_status = rep(NA_character_, length(rows)),
      agent_review_issue_codes = rep(NA_character_, length(rows)),
      agent_review_action = rep(NA_character_, length(rows)),
      agent_review_confidence = rep(NA_real_, length(rows)),
      agent_review_explanation = rep(NA_character_, length(rows))
    )
  } else {
    tibble::tibble(
      unit_id = integer(), file = character(),
      staged_file = character(), unit_type = character(),
      tier = character(), dataset = character(),
      gate_reached = character(), evidence_basis = character(),
      reason = character(), flags = character(),
      code = character(),
      lint_errors = integer(), lint_warnings = integer(),
      agent_review_status = character(),
      agent_review_issue_codes = character(),
      agent_review_action = character(),
      agent_review_confidence = numeric(),
      agent_review_explanation = character()
    )
  }

  helper_path <- file.path(out_dir, "sas2r-helpers.R")
  r_hash <- if (file.exists(helper_path)) {
    migration_hash(readLines(helper_path, warn = FALSE))
  } else {
    NA_character_
  }
  r_ver <- as.character(utils::packageVersion("sas2r"))

  attr(manifest, "runtime_version") <- r_ver
  attr(manifest, "runtime_hash") <- r_hash
  attr(manifest, "helper_override") <- NA_character_

  structure(list(manifest = manifest,
                 out_dir = out_dir,
                 order = project$order,
                 runtime_version = r_ver,
                 runtime_hash = r_hash,
                 helper_override = NA_character_),
            class = "sas2r_transpilation")
}


#' Print a sas2r transpilation summary
#'
#' @param x A `sas2r_transpilation` object.
#' @param ... Additional arguments (ignored).
#' @return The input `x`, invisibly.
#' @export
print.sas2r_transpilation <- function(x, ...) {
  m <- x$manifest
  cli::cli_h1("sas2r deterministic transpilation")
  cli::cli_text("{sum(m$tier == 't1')} unit{?s} emitted (T1), {sum(m$tier == 'stub')} stubbed")
  if (any(m$tier == "stub")) {
    for (r in unique(m$reason[m$tier == "stub"])) {
      cli::cli_alert_warning("{sum(m$reason == r, na.rm = TRUE)} unit{?s}: {r}")
    }
  }
  cli::cli_text("staged in {.file {x$out_dir}} -- NOT verified; run the ladder next")
  invisible(x)
}
